# This file was auto-generated by Fern from our API Definition.

import typing

ListEventsRequestSourceItem = typing.Union[
    typing.Literal["browser", "network", "runtime", "agent", "tool", "system"], typing.Any
]
