# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.environment import Environment
from .raw_client import AsyncRawRuntimeClient, RawRuntimeClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RuntimeClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRuntimeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRuntimeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRuntimeClient
        """
        return self._raw_client

    def attach(
        self,
        environment_id: str,
        *,
        runtime_id: str,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Environment:
        """
        Attach one Runtime from the same Space to an Environment.

        Parameters
        ----------
        environment_id : str

        runtime_id : str
            Unique browser identifier generated by BCTRL.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Environment
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.environments.runtime.attach(
            environment_id="environmentId",
            runtime_id="runtimeId",
        )
        """
        _response = self._raw_client.attach(
            environment_id, runtime_id=runtime_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data


class AsyncRuntimeClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRuntimeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRuntimeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRuntimeClient
        """
        return self._raw_client

    async def attach(
        self,
        environment_id: str,
        *,
        runtime_id: str,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Environment:
        """
        Attach one Runtime from the same Space to an Environment.

        Parameters
        ----------
        environment_id : str

        runtime_id : str
            Unique browser identifier generated by BCTRL.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Environment
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.environments.runtime.attach(
                environment_id="environmentId",
                runtime_id="runtimeId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.attach(
            environment_id, runtime_id=runtime_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data
