# This file was auto-generated by Fern from our API Definition.

import contextlib
import typing
from json.decoder import JSONDecodeError
from logging import error, warning

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.datetime_utils import serialize_datetime
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.http_sse._api import EventSource
from ...core.jsonable_encoder import quote_path_param
from ...core.parse_error import ParsingError
from ...core.pydantic_utilities import parse_obj_as, parse_sse_obj
from ...core.request_options import RequestOptions
from ...core.serialization import convert_and_respect_annotation_metadata
from ...errors.bad_request_error import BadRequestError
from ...errors.forbidden_error import ForbiddenError
from ...errors.not_found_error import NotFoundError
from ...errors.too_many_requests_error import TooManyRequestsError
from ...errors.unauthorized_error import UnauthorizedError
from ...types.event import Event
from ...types.list_events_request_category import ListEventsRequestCategory
from ...types.list_events_request_channel import ListEventsRequestChannel
from ...types.list_events_request_outcome import ListEventsRequestOutcome
from ...types.rfc3339timestamp import Rfc3339Timestamp
from ...types.stream_events_request_category import StreamEventsRequestCategory
from ...types.stream_events_request_channel import StreamEventsRequestChannel
from ...types.stream_events_request_outcome import StreamEventsRequestOutcome
from ...types.tasks_events_list_response import TasksEventsListResponse
from .types.list_events_request_actor_type import ListEventsRequestActorType
from .types.list_events_request_order import ListEventsRequestOrder
from .types.stream_events_request_actor_type import StreamEventsRequestActorType
from pydantic import ValidationError


class RawEventsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        task_id: str,
        *,
        category: typing.Optional[ListEventsRequestCategory] = None,
        type: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        actor: typing.Optional[str] = None,
        actor_type: typing.Optional[ListEventsRequestActorType] = None,
        channel: typing.Optional[ListEventsRequestChannel] = None,
        outcome: typing.Optional[ListEventsRequestOutcome] = None,
        from_: typing.Optional[Rfc3339Timestamp] = None,
        to: typing.Optional[Rfc3339Timestamp] = None,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListEventsRequestOrder] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TasksEventsListResponse]:
        """
        Read the Task’s canonical history. Events inside its runtimes remain in each Run log.

        Parameters
        ----------
        task_id : str
            Unique task identifier generated by BCTRL.

        category : typing.Optional[ListEventsRequestCategory]

        type : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        actor : typing.Optional[str]
            Actor ID.

        actor_type : typing.Optional[ListEventsRequestActorType]

        channel : typing.Optional[ListEventsRequestChannel]

        outcome : typing.Optional[ListEventsRequestOutcome]

        from_ : typing.Optional[Rfc3339Timestamp]

        to : typing.Optional[Rfc3339Timestamp]

        cursor : typing.Optional[str]

        order : typing.Optional[ListEventsRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TasksEventsListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/tasks/{quote_path_param(task_id)}/events",
            method="GET",
            params={
                "category": convert_and_respect_annotation_metadata(
                    object_=category, annotation=ListEventsRequestCategory, direction="write"
                ),
                "type": type,
                "actor": actor,
                "actorType": actor_type,
                "channel": convert_and_respect_annotation_metadata(
                    object_=channel, annotation=ListEventsRequestChannel, direction="write"
                ),
                "outcome": convert_and_respect_annotation_metadata(
                    object_=outcome, annotation=ListEventsRequestOutcome, direction="write"
                ),
                "from": serialize_datetime(from_) if from_ is not None else None,
                "to": serialize_datetime(to) if to is not None else None,
                "cursor": cursor,
                "order": order,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TasksEventsListResponse,
                    parse_obj_as(
                        type_=TasksEventsListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.contextmanager
    def stream(
        self,
        task_id: str,
        *,
        category: typing.Optional[StreamEventsRequestCategory] = None,
        type: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        actor: typing.Optional[str] = None,
        actor_type: typing.Optional[StreamEventsRequestActorType] = None,
        channel: typing.Optional[StreamEventsRequestChannel] = None,
        outcome: typing.Optional[StreamEventsRequestOutcome] = None,
        from_: typing.Optional[Rfc3339Timestamp] = None,
        to: typing.Optional[Rfc3339Timestamp] = None,
        after: typing.Optional[str] = None,
        last_event_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[HttpResponse[typing.Iterator[Event]]]:
        """
        Resume canonical Task history by Event ID. The stream stays pinned to this Task and rechecks reader authority.

        Parameters
        ----------
        task_id : str
            Unique task identifier generated by BCTRL.

        category : typing.Optional[StreamEventsRequestCategory]

        type : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        actor : typing.Optional[str]
            Actor ID.

        actor_type : typing.Optional[StreamEventsRequestActorType]

        channel : typing.Optional[StreamEventsRequestChannel]

        outcome : typing.Optional[StreamEventsRequestOutcome]

        from_ : typing.Optional[Rfc3339Timestamp]

        to : typing.Optional[Rfc3339Timestamp]

        after : typing.Optional[str]
            Resume after this Event ID from the same Task history.

        last_event_id : typing.Optional[str]
            Optional last delivered event identifier used to resume an SSE stream.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[HttpResponse[typing.Iterator[Event]]]
            Server-Sent Events with canonical Event IDs; heartbeats are comments.
        """
        with self._client_wrapper.httpx_client.stream(
            f"v1/tasks/{quote_path_param(task_id)}/events/stream",
            method="GET",
            params={
                "category": convert_and_respect_annotation_metadata(
                    object_=category, annotation=StreamEventsRequestCategory, direction="write"
                ),
                "type": type,
                "actor": actor,
                "actorType": actor_type,
                "channel": convert_and_respect_annotation_metadata(
                    object_=channel, annotation=StreamEventsRequestChannel, direction="write"
                ),
                "outcome": convert_and_respect_annotation_metadata(
                    object_=outcome, annotation=StreamEventsRequestOutcome, direction="write"
                ),
                "from": serialize_datetime(from_) if from_ is not None else None,
                "to": serialize_datetime(to) if to is not None else None,
                "after": after,
            },
            headers={
                "Last-Event-ID": str(last_event_id) if last_event_id is not None else None,
            },
            request_options=request_options,
        ) as _response:

            def _stream() -> HttpResponse[typing.Iterator[Event]]:
                try:
                    if 200 <= _response.status_code < 300:

                        def _iter():
                            _event_source = EventSource(_response)
                            for _sse in _event_source.iter_sse():
                                if _sse.data == None:
                                    return
                                if len(_sse.data) == 0:
                                    continue
                                try:
                                    yield typing.cast(
                                        Event,
                                        parse_sse_obj(
                                            sse=_sse,
                                            type_=Event,  # type: ignore
                                        ),
                                    )
                                except JSONDecodeError as e:
                                    warning(f"Skipping SSE event with invalid JSON: {e}, sse: {_sse!r}")
                                except (TypeError, ValueError, KeyError, AttributeError) as e:
                                    warning(
                                        f"Skipping SSE event due to model construction error: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                                except Exception as e:
                                    error(
                                        f"Unexpected error processing SSE event: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                            return

                        return HttpResponse(response=_response, data=_iter())
                    _response.read()
                    if _response.status_code == 400:
                        raise BadRequestError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                parse_obj_as(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 401:
                        raise UnauthorizedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                parse_obj_as(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 403:
                        raise ForbiddenError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                parse_obj_as(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 404:
                        raise NotFoundError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                parse_obj_as(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 429:
                        raise TooManyRequestsError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                parse_obj_as(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield _stream()


class AsyncRawEventsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        task_id: str,
        *,
        category: typing.Optional[ListEventsRequestCategory] = None,
        type: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        actor: typing.Optional[str] = None,
        actor_type: typing.Optional[ListEventsRequestActorType] = None,
        channel: typing.Optional[ListEventsRequestChannel] = None,
        outcome: typing.Optional[ListEventsRequestOutcome] = None,
        from_: typing.Optional[Rfc3339Timestamp] = None,
        to: typing.Optional[Rfc3339Timestamp] = None,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListEventsRequestOrder] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TasksEventsListResponse]:
        """
        Read the Task’s canonical history. Events inside its runtimes remain in each Run log.

        Parameters
        ----------
        task_id : str
            Unique task identifier generated by BCTRL.

        category : typing.Optional[ListEventsRequestCategory]

        type : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        actor : typing.Optional[str]
            Actor ID.

        actor_type : typing.Optional[ListEventsRequestActorType]

        channel : typing.Optional[ListEventsRequestChannel]

        outcome : typing.Optional[ListEventsRequestOutcome]

        from_ : typing.Optional[Rfc3339Timestamp]

        to : typing.Optional[Rfc3339Timestamp]

        cursor : typing.Optional[str]

        order : typing.Optional[ListEventsRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TasksEventsListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/tasks/{quote_path_param(task_id)}/events",
            method="GET",
            params={
                "category": convert_and_respect_annotation_metadata(
                    object_=category, annotation=ListEventsRequestCategory, direction="write"
                ),
                "type": type,
                "actor": actor,
                "actorType": actor_type,
                "channel": convert_and_respect_annotation_metadata(
                    object_=channel, annotation=ListEventsRequestChannel, direction="write"
                ),
                "outcome": convert_and_respect_annotation_metadata(
                    object_=outcome, annotation=ListEventsRequestOutcome, direction="write"
                ),
                "from": serialize_datetime(from_) if from_ is not None else None,
                "to": serialize_datetime(to) if to is not None else None,
                "cursor": cursor,
                "order": order,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TasksEventsListResponse,
                    parse_obj_as(
                        type_=TasksEventsListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.asynccontextmanager
    async def stream(
        self,
        task_id: str,
        *,
        category: typing.Optional[StreamEventsRequestCategory] = None,
        type: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        actor: typing.Optional[str] = None,
        actor_type: typing.Optional[StreamEventsRequestActorType] = None,
        channel: typing.Optional[StreamEventsRequestChannel] = None,
        outcome: typing.Optional[StreamEventsRequestOutcome] = None,
        from_: typing.Optional[Rfc3339Timestamp] = None,
        to: typing.Optional[Rfc3339Timestamp] = None,
        after: typing.Optional[str] = None,
        last_event_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[Event]]]:
        """
        Resume canonical Task history by Event ID. The stream stays pinned to this Task and rechecks reader authority.

        Parameters
        ----------
        task_id : str
            Unique task identifier generated by BCTRL.

        category : typing.Optional[StreamEventsRequestCategory]

        type : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        actor : typing.Optional[str]
            Actor ID.

        actor_type : typing.Optional[StreamEventsRequestActorType]

        channel : typing.Optional[StreamEventsRequestChannel]

        outcome : typing.Optional[StreamEventsRequestOutcome]

        from_ : typing.Optional[Rfc3339Timestamp]

        to : typing.Optional[Rfc3339Timestamp]

        after : typing.Optional[str]
            Resume after this Event ID from the same Task history.

        last_event_id : typing.Optional[str]
            Optional last delivered event identifier used to resume an SSE stream.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[Event]]]
            Server-Sent Events with canonical Event IDs; heartbeats are comments.
        """
        async with self._client_wrapper.httpx_client.stream(
            f"v1/tasks/{quote_path_param(task_id)}/events/stream",
            method="GET",
            params={
                "category": convert_and_respect_annotation_metadata(
                    object_=category, annotation=StreamEventsRequestCategory, direction="write"
                ),
                "type": type,
                "actor": actor,
                "actorType": actor_type,
                "channel": convert_and_respect_annotation_metadata(
                    object_=channel, annotation=StreamEventsRequestChannel, direction="write"
                ),
                "outcome": convert_and_respect_annotation_metadata(
                    object_=outcome, annotation=StreamEventsRequestOutcome, direction="write"
                ),
                "from": serialize_datetime(from_) if from_ is not None else None,
                "to": serialize_datetime(to) if to is not None else None,
                "after": after,
            },
            headers={
                "Last-Event-ID": str(last_event_id) if last_event_id is not None else None,
            },
            request_options=request_options,
        ) as _response:

            async def _stream() -> AsyncHttpResponse[typing.AsyncIterator[Event]]:
                try:
                    if 200 <= _response.status_code < 300:

                        async def _iter():
                            _event_source = EventSource(_response)
                            async for _sse in _event_source.aiter_sse():
                                if _sse.data == None:
                                    return
                                if len(_sse.data) == 0:
                                    continue
                                try:
                                    yield typing.cast(
                                        Event,
                                        parse_sse_obj(
                                            sse=_sse,
                                            type_=Event,  # type: ignore
                                        ),
                                    )
                                except JSONDecodeError as e:
                                    warning(f"Skipping SSE event with invalid JSON: {e}, sse: {_sse!r}")
                                except (TypeError, ValueError, KeyError, AttributeError) as e:
                                    warning(
                                        f"Skipping SSE event due to model construction error: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                                except Exception as e:
                                    error(
                                        f"Unexpected error processing SSE event: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                            return

                        return AsyncHttpResponse(response=_response, data=_iter())
                    await _response.aread()
                    if _response.status_code == 400:
                        raise BadRequestError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                parse_obj_as(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 401:
                        raise UnauthorizedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                parse_obj_as(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 403:
                        raise ForbiddenError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                parse_obj_as(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 404:
                        raise NotFoundError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                parse_obj_as(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 429:
                        raise TooManyRequestsError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Any,
                                parse_obj_as(
                                    type_=typing.Any,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield await _stream()
