# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.browser_resource import BrowserResource
from ...types.revoke_connections_request_space_id import RevokeConnectionsRequestSpaceId
from .raw_client import AsyncRawConnectionsClient, RawConnectionsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ConnectionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConnectionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConnectionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConnectionsClient
        """
        return self._raw_client

    def revoke(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[RevokeConnectionsRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BrowserResource:
        """
        Invalidate every existing connection URL for the current Run and issue connections in a new credential generation. Refresh the browser before reconnecting.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[RevokeConnectionsRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BrowserResource
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.connections.revoke(
            browser_id="browserId",
        )
        """
        _response = self._raw_client.revoke(
            browser_id, space_id=space_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data


class AsyncConnectionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConnectionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConnectionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConnectionsClient
        """
        return self._raw_client

    async def revoke(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[RevokeConnectionsRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BrowserResource:
        """
        Invalidate every existing connection URL for the current Run and issue connections in a new credential generation. Refresh the browser before reconnecting.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[RevokeConnectionsRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BrowserResource
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.connections.revoke(
                browser_id="browserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke(
            browser_id, space_id=space_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data
