# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.agent_turn_accepted import AgentTurnAccepted
from ...types.conversation_variables import ConversationVariables
from .raw_client import AsyncRawMessagesClient, RawMessagesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMessagesClient
        """
        return self._raw_client

    def create(
        self,
        conversation_id: str,
        *,
        text: str,
        idempotency_key: typing.Optional[str] = None,
        file_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        model: typing.Optional[str] = OMIT,
        page_id: typing.Optional[str] = OMIT,
        variables: typing.Optional[ConversationVariables] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentTurnAccepted:
        """
        Append a user message and start one agent turn.

        Parameters
        ----------
        conversation_id : str
            Unique conversation identifier generated by BCTRL.

        text : str

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        file_ids : typing.Optional[typing.Sequence[str]]

        model : typing.Optional[str]

        page_id : typing.Optional[str]
            Unique page identifier generated by BCTRL.

        variables : typing.Optional[ConversationVariables]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentTurnAccepted
            Accepted

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.conversations.messages.create(
            conversation_id="conversationId",
            text="text",
        )
        """
        _response = self._raw_client.create(
            conversation_id,
            text=text,
            idempotency_key=idempotency_key,
            file_ids=file_ids,
            model=model,
            page_id=page_id,
            variables=variables,
            request_options=request_options,
        )
        return _response.data


class AsyncMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMessagesClient
        """
        return self._raw_client

    async def create(
        self,
        conversation_id: str,
        *,
        text: str,
        idempotency_key: typing.Optional[str] = None,
        file_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        model: typing.Optional[str] = OMIT,
        page_id: typing.Optional[str] = OMIT,
        variables: typing.Optional[ConversationVariables] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentTurnAccepted:
        """
        Append a user message and start one agent turn.

        Parameters
        ----------
        conversation_id : str
            Unique conversation identifier generated by BCTRL.

        text : str

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        file_ids : typing.Optional[typing.Sequence[str]]

        model : typing.Optional[str]

        page_id : typing.Optional[str]
            Unique page identifier generated by BCTRL.

        variables : typing.Optional[ConversationVariables]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentTurnAccepted
            Accepted

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.conversations.messages.create(
                conversation_id="conversationId",
                text="text",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            conversation_id,
            text=text,
            idempotency_key=idempotency_key,
            file_ids=file_ids,
            model=model,
            page_id=page_id,
            variables=variables,
            request_options=request_options,
        )
        return _response.data
