# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.conversation_delete_response import ConversationDeleteResponse
from ..types.conversation_list_response import ConversationListResponse
from ..types.conversation_record import ConversationRecord
from ..types.json_object import JsonObject
from ..types.rfc3339timestamp import Rfc3339Timestamp
from .raw_client import AsyncRawConversationsClient, RawConversationsClient
from .types.list_conversations_request_order import ListConversationsRequestOrder

if typing.TYPE_CHECKING:
    from .events.client import AsyncEventsClient, EventsClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ConversationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConversationsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._events: typing.Optional[EventsClient] = None

    @property
    def with_raw_response(self) -> RawConversationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConversationsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListConversationsRequestOrder] = None,
        limit: typing.Optional[int] = None,
        space_id: typing.Optional[str] = None,
        agent: typing.Optional[str] = None,
        from_: typing.Optional[Rfc3339Timestamp] = None,
        to: typing.Optional[Rfc3339Timestamp] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConversationListResponse:
        """
        List durable agent conversations.

        Parameters
        ----------
        cursor : typing.Optional[str]

        order : typing.Optional[ListConversationsRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        space_id : typing.Optional[str]
            Filter by a prefixed space ID, or pass `default` to use the caller default space.

        agent : typing.Optional[str]

        from_ : typing.Optional[Rfc3339Timestamp]

        to : typing.Optional[Rfc3339Timestamp]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConversationListResponse
            OK

        Examples
        --------
        import datetime

        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.conversations.list(
            from_=datetime.datetime.fromisoformat(
                "2026-07-26 12:00:00+00:00",
            ),
            to=datetime.datetime.fromisoformat(
                "2026-07-26 12:00:00+00:00",
            ),
        )
        """
        _response = self._raw_client.list(
            cursor=cursor,
            order=order,
            limit=limit,
            space_id=space_id,
            agent=agent,
            from_=from_,
            to=to,
            request_options=request_options,
        )
        return _response.data

    def get(
        self, conversation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ConversationRecord:
        """
        Get a runtime-free Conversation record; read its events for history.

        Parameters
        ----------
        conversation_id : str
            Unique conversation identifier generated by BCTRL.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConversationRecord
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.conversations.get(
            conversation_id="conversationId",
        )
        """
        _response = self._raw_client.get(conversation_id, request_options=request_options)
        return _response.data

    def delete(
        self,
        conversation_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConversationDeleteResponse:
        """
        Delete an idle Conversation and retire its workspace.

        Parameters
        ----------
        conversation_id : str
            Unique conversation identifier generated by BCTRL.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConversationDeleteResponse
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.conversations.delete(
            conversation_id="conversationId",
        )
        """
        _response = self._raw_client.delete(
            conversation_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def update(
        self,
        conversation_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        metadata: typing.Optional[JsonObject] = OMIT,
        title: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConversationRecord:
        """
        Update a Conversation title and metadata.

        Parameters
        ----------
        conversation_id : str
            Unique conversation identifier generated by BCTRL.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        metadata : typing.Optional[JsonObject]

        title : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConversationRecord
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.conversations.update(
            conversation_id="conversationId",
        )
        """
        _response = self._raw_client.update(
            conversation_id,
            idempotency_key=idempotency_key,
            metadata=metadata,
            title=title,
            request_options=request_options,
        )
        return _response.data

    @property
    def events(self):
        if self._events is None:
            from .events.client import EventsClient  # noqa: E402

            self._events = EventsClient(client_wrapper=self._client_wrapper)
        return self._events


class AsyncConversationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConversationsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._events: typing.Optional[AsyncEventsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawConversationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConversationsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListConversationsRequestOrder] = None,
        limit: typing.Optional[int] = None,
        space_id: typing.Optional[str] = None,
        agent: typing.Optional[str] = None,
        from_: typing.Optional[Rfc3339Timestamp] = None,
        to: typing.Optional[Rfc3339Timestamp] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConversationListResponse:
        """
        List durable agent conversations.

        Parameters
        ----------
        cursor : typing.Optional[str]

        order : typing.Optional[ListConversationsRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        space_id : typing.Optional[str]
            Filter by a prefixed space ID, or pass `default` to use the caller default space.

        agent : typing.Optional[str]

        from_ : typing.Optional[Rfc3339Timestamp]

        to : typing.Optional[Rfc3339Timestamp]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConversationListResponse
            OK

        Examples
        --------
        import asyncio
        import datetime

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.conversations.list(
                from_=datetime.datetime.fromisoformat(
                    "2026-07-26 12:00:00+00:00",
                ),
                to=datetime.datetime.fromisoformat(
                    "2026-07-26 12:00:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            cursor=cursor,
            order=order,
            limit=limit,
            space_id=space_id,
            agent=agent,
            from_=from_,
            to=to,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self, conversation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ConversationRecord:
        """
        Get a runtime-free Conversation record; read its events for history.

        Parameters
        ----------
        conversation_id : str
            Unique conversation identifier generated by BCTRL.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConversationRecord
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.conversations.get(
                conversation_id="conversationId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(conversation_id, request_options=request_options)
        return _response.data

    async def delete(
        self,
        conversation_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConversationDeleteResponse:
        """
        Delete an idle Conversation and retire its workspace.

        Parameters
        ----------
        conversation_id : str
            Unique conversation identifier generated by BCTRL.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConversationDeleteResponse
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.conversations.delete(
                conversation_id="conversationId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            conversation_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def update(
        self,
        conversation_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        metadata: typing.Optional[JsonObject] = OMIT,
        title: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConversationRecord:
        """
        Update a Conversation title and metadata.

        Parameters
        ----------
        conversation_id : str
            Unique conversation identifier generated by BCTRL.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        metadata : typing.Optional[JsonObject]

        title : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConversationRecord
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.conversations.update(
                conversation_id="conversationId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            conversation_id,
            idempotency_key=idempotency_key,
            metadata=metadata,
            title=title,
            request_options=request_options,
        )
        return _response.data

    @property
    def events(self):
        if self._events is None:
            from .events.client import AsyncEventsClient  # noqa: E402

            self._events = AsyncEventsClient(client_wrapper=self._client_wrapper)
        return self._events
