# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .a2a_agent_card_capabilities import A2AAgentCardCapabilities
from .a2a_agent_card_provider import A2AAgentCardProvider
from .a2a_agent_card_skills_item import A2AAgentCardSkillsItem
from .a2a_agent_card_supported_interfaces_item import A2AAgentCardSupportedInterfacesItem
from .json_object import JsonObject


class A2AAgentCard(UniversalBaseModel):
    capabilities: A2AAgentCardCapabilities
    default_input_modes: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="defaultInputModes"), pydantic.Field(alias="defaultInputModes")
    ]
    default_output_modes: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="defaultOutputModes"), pydantic.Field(alias="defaultOutputModes")
    ]
    description: str
    name: str
    provider: A2AAgentCardProvider
    security_requirements: typing_extensions.Annotated[
        typing.List[JsonObject],
        FieldMetadata(alias="securityRequirements"),
        pydantic.Field(alias="securityRequirements"),
    ]
    security_schemes: typing_extensions.Annotated[
        JsonObject, FieldMetadata(alias="securitySchemes"), pydantic.Field(alias="securitySchemes")
    ]
    skills: typing.List[A2AAgentCardSkillsItem]
    supported_interfaces: typing_extensions.Annotated[
        typing.List[A2AAgentCardSupportedInterfacesItem],
        FieldMetadata(alias="supportedInterfaces"),
        pydantic.Field(alias="supportedInterfaces"),
    ]
    version: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
