# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .account_usage_blocked_reasons_item import AccountUsageBlockedReasonsItem
from .account_usage_credits import AccountUsageCredits
from .account_usage_cycle import AccountUsageCycle
from .account_usage_object import AccountUsageObject
from .rfc3339timestamp import Rfc3339Timestamp


class AccountUsage(UniversalBaseModel):
    blocked_reasons: typing_extensions.Annotated[
        typing.List[AccountUsageBlockedReasonsItem],
        FieldMetadata(alias="blockedReasons"),
        pydantic.Field(alias="blockedReasons"),
    ]
    computed_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="computedAt"), pydantic.Field(alias="computedAt")
    ]
    credits: AccountUsageCredits
    cycle: AccountUsageCycle
    is_blocked: typing_extensions.Annotated[bool, FieldMetadata(alias="isBlocked"), pydantic.Field(alias="isBlocked")]
    object: AccountUsageObject
    organization_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="organizationId"), pydantic.Field(alias="organizationId")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
