# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .agent_turn_accepted_object import AgentTurnAcceptedObject
from .agent_turn_accepted_status import AgentTurnAcceptedStatus


class AgentTurnAccepted(UniversalBaseModel):
    message_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="messageId"),
        pydantic.Field(alias="messageId", description="Unique message identifier generated by BCTRL."),
    ]
    """
    Unique message identifier generated by BCTRL.
    """

    object: AgentTurnAcceptedObject
    run_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="runId"),
        pydantic.Field(alias="runId", description="Unique run identifier generated by BCTRL."),
    ]
    """
    Unique run identifier generated by BCTRL.
    """

    span_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="spanId"),
        pydantic.Field(alias="spanId", description="Unique traceSpan identifier generated by BCTRL."),
    ]
    """
    Unique traceSpan identifier generated by BCTRL.
    """

    status: AgentTurnAcceptedStatus
    stream_cursor: typing_extensions.Annotated[
        str, FieldMetadata(alias="streamCursor"), pydantic.Field(alias="streamCursor")
    ]
    turn_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="turnId"),
        pydantic.Field(alias="turnId", description="Unique agentTurn identifier generated by BCTRL."),
    ]
    """
    Unique agentTurn identifier generated by BCTRL.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
