# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ai_stored_model_selection_cache_control_ttl import AiStoredModelSelectionCacheControlTtl
from .ai_stored_model_selection_cache_control_type import AiStoredModelSelectionCacheControlType


class AiStoredModelSelectionCacheControl(UniversalBaseModel):
    ttl: typing.Optional[AiStoredModelSelectionCacheControlTtl] = None
    type: AiStoredModelSelectionCacheControlType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
