# This file was auto-generated by Fern from our API Definition.

import typing

from .batch_computer_request_space_id_one import BatchComputerRequestSpaceIdOne

BatchComputerRequestSpaceId = typing.Union[str, BatchComputerRequestSpaceIdOne]
