# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .browser_inline_custom_proxy_url_input_dns_resolution import BrowserInlineCustomProxyUrlInputDnsResolution
from .browser_inline_custom_proxy_url_input_type import BrowserInlineCustomProxyUrlInputType
from .browser_inline_custom_proxy_url_input_udp_mode import BrowserInlineCustomProxyUrlInputUdpMode


class BrowserInlineCustomProxyUrlInput(UniversalBaseModel):
    dns_resolution: typing_extensions.Annotated[
        typing.Optional[BrowserInlineCustomProxyUrlInputDnsResolution],
        FieldMetadata(alias="dnsResolution"),
        pydantic.Field(alias="dnsResolution"),
    ] = None
    password: typing.Optional[str] = None
    type: typing.Optional[BrowserInlineCustomProxyUrlInputType] = None
    udp_mode: typing_extensions.Annotated[
        typing.Optional[BrowserInlineCustomProxyUrlInputUdpMode],
        FieldMetadata(alias="udpMode"),
        pydantic.Field(alias="udpMode"),
    ] = None
    url: str
    username: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
