# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BrowserExtensionCreateRequest2(UniversalBaseModel):
    file: bytes = pydantic.Field()
    """
    Chromium browser extension package (.crx).
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional display name. Defaults to manifest.name.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
