# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .browser_page_deleted_object import BrowserPageDeletedObject


class BrowserPageDeleted(UniversalBaseModel):
    deleted: bool
    id: str = pydantic.Field()
    """
    Unique page identifier generated by BCTRL.
    """

    object: BrowserPageDeletedObject
    run_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="runId"),
        pydantic.Field(alias="runId", description="Unique run identifier generated by BCTRL."),
    ]
    """
    Unique run identifier generated by BCTRL.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
