# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .computer_action_request_click_button import ComputerActionRequestClickButton
from .computer_action_request_scroll_direction import ComputerActionRequestScrollDirection


class ComputerActionRequest_Screenshot(UniversalBaseModel):
    action: typing.Literal["screenshot"] = "screenshot"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ComputerActionRequest_Click(UniversalBaseModel):
    action: typing.Literal["click"] = "click"
    button: typing.Optional[ComputerActionRequestClickButton] = None
    click_count: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="clickCount"), pydantic.Field(alias="clickCount")
    ] = None
    coordinate: typing.Optional[typing.List[typing.Any]] = None
    modifiers: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ComputerActionRequest_DoubleClick(UniversalBaseModel):
    action: typing.Literal["doubleClick"] = "doubleClick"
    coordinate: typing.Optional[typing.List[typing.Any]] = None
    modifiers: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ComputerActionRequest_Move(UniversalBaseModel):
    action: typing.Literal["move"] = "move"
    coordinate: typing.List[typing.Any]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ComputerActionRequest_Drag(UniversalBaseModel):
    action: typing.Literal["drag"] = "drag"
    coordinate: typing.List[typing.Any]
    modifiers: typing.Optional[str] = None
    path: typing.Optional[typing.List[typing.List[typing.Any]]] = None
    start_coordinate: typing_extensions.Annotated[
        typing.Optional[typing.List[typing.Any]],
        FieldMetadata(alias="startCoordinate"),
        pydantic.Field(alias="startCoordinate"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ComputerActionRequest_Scroll(UniversalBaseModel):
    action: typing.Literal["scroll"] = "scroll"
    amount: int
    coordinate: typing.Optional[typing.List[typing.Any]] = None
    direction: ComputerActionRequestScrollDirection
    modifiers: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ComputerActionRequest_Type(UniversalBaseModel):
    action: typing.Literal["type"] = "type"
    text: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ComputerActionRequest_Key(UniversalBaseModel):
    action: typing.Literal["key"] = "key"
    keys: str
    repeat: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ComputerActionRequest_Wait(UniversalBaseModel):
    action: typing.Literal["wait"] = "wait"
    duration: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ComputerActionRequest_Cursor(UniversalBaseModel):
    action: typing.Literal["cursor"] = "cursor"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


ComputerActionRequest = typing_extensions.Annotated[
    typing.Union[
        ComputerActionRequest_Screenshot,
        ComputerActionRequest_Click,
        ComputerActionRequest_DoubleClick,
        ComputerActionRequest_Move,
        ComputerActionRequest_Drag,
        ComputerActionRequest_Scroll,
        ComputerActionRequest_Type,
        ComputerActionRequest_Key,
        ComputerActionRequest_Wait,
        ComputerActionRequest_Cursor,
    ],
    pydantic.Field(discriminator="action"),
]
