# This file was auto-generated by Fern from our API Definition.

import typing

ComputerUseOutputAction = typing.Union[
    typing.Literal[
        "screenshot",
        "left_click",
        "right_click",
        "middle_click",
        "double_click",
        "triple_click",
        "type",
        "key",
        "mouse_move",
        "scroll",
        "left_click_drag",
        "wait",
        "cursor_position",
    ],
    typing.Any,
]
