# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .rfc3339timestamp import Rfc3339Timestamp


class ConversationEventTurnTimedOut(UniversalBaseModel):
    conversation_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="conversationId"),
        pydantic.Field(alias="conversationId", description="Unique conversation identifier generated by BCTRL."),
    ]
    """
    Unique conversation identifier generated by BCTRL.
    """

    id: str
    message_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="messageId"),
        pydantic.Field(alias="messageId", description="Unique message identifier generated by BCTRL."),
    ] = None
    """
    Unique message identifier generated by BCTRL.
    """

    timestamp: Rfc3339Timestamp
    turn_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="turnId"),
        pydantic.Field(alias="turnId", description="Unique agentTurn identifier generated by BCTRL."),
    ]
    """
    Unique agentTurn identifier generated by BCTRL.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
