# This file was auto-generated by Fern from our API Definition.

import typing

ConversationEventTurnCompletedExecutionMode = typing.Union[
    typing.Literal["agent", "deterministic", "assisted"], typing.Any
]
