# This file was auto-generated by Fern from our API Definition.

import typing

ConversationEventTurnCompletedReplayStatus = typing.Union[typing.Literal["bypass", "miss", "hit", "healed"], typing.Any]
