# This file was auto-generated by Fern from our API Definition.

import typing

from .cursor_computer_request_space_id_one import CursorComputerRequestSpaceIdOne

CursorComputerRequestSpaceId = typing.Union[str, CursorComputerRequestSpaceIdOne]
