# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_tool_implementation_code_language import CustomToolImplementationCodeLanguage


class CustomToolImplementationCode(UniversalBaseModel):
    language: CustomToolImplementationCodeLanguage
    timeout_ms: typing_extensions.Annotated[int, FieldMetadata(alias="timeoutMs"), pydantic.Field(alias="timeoutMs")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
