# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .drain_create_response_categories_item import DrainCreateResponseCategoriesItem
from .drain_create_response_object import DrainCreateResponseObject
from .drain_destination_output import DrainDestinationOutput
from .drain_status import DrainStatus
from .rfc3339timestamp import Rfc3339Timestamp


class DrainCreateResponse(UniversalBaseModel):
    categories: typing.List[DrainCreateResponseCategoriesItem]
    created_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    destination: DrainDestinationOutput
    enabled: bool
    id: str = pydantic.Field()
    """
    Unique drain identifier generated by BCTRL.
    """

    name: typing.Optional[str] = None
    object: DrainCreateResponseObject
    secret: typing.Optional[str] = None
    status: DrainStatus
    subaccount_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="subaccountId"), pydantic.Field(alias="subaccountId")
    ] = None
    updated_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
