# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .rfc3339timestamp import Rfc3339Timestamp


class DrainStatus(UniversalBaseModel):
    bytes_sent: typing_extensions.Annotated[int, FieldMetadata(alias="bytesSent"), pydantic.Field(alias="bytesSent")]
    events_sent: typing_extensions.Annotated[int, FieldMetadata(alias="eventsSent"), pydantic.Field(alias="eventsSent")]
    last_delivery_at: typing_extensions.Annotated[
        typing.Optional[Rfc3339Timestamp], FieldMetadata(alias="lastDeliveryAt"), pydantic.Field(alias="lastDeliveryAt")
    ] = None
    last_error: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="lastError"), pydantic.Field(alias="lastError")
    ] = None
    last_error_at: typing_extensions.Annotated[
        typing.Optional[Rfc3339Timestamp], FieldMetadata(alias="lastErrorAt"), pydantic.Field(alias="lastErrorAt")
    ] = None
    next_attempt_at: typing_extensions.Annotated[
        typing.Optional[Rfc3339Timestamp], FieldMetadata(alias="nextAttemptAt"), pydantic.Field(alias="nextAttemptAt")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
