# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .environment_exec_accepted_object import EnvironmentExecAcceptedObject
from .environment_exec_accepted_status import EnvironmentExecAcceptedStatus
from .rfc3339timestamp import Rfc3339Timestamp


class EnvironmentExecAccepted(UniversalBaseModel):
    created_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    environment_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="environmentId"),
        pydantic.Field(alias="environmentId", description="Unique environment identifier generated by BCTRL."),
    ]
    """
    Unique environment identifier generated by BCTRL.
    """

    id: str = pydantic.Field()
    """
    Unique environmentExec identifier generated by BCTRL.
    """

    object: EnvironmentExecAcceptedObject
    status: EnvironmentExecAcceptedStatus
    updated_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
