# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .environment_exec_object import EnvironmentExecObject
from .environment_exec_status import EnvironmentExecStatus
from .rfc3339timestamp import Rfc3339Timestamp


class EnvironmentExec(UniversalBaseModel):
    created_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    environment_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="environmentId"),
        pydantic.Field(alias="environmentId", description="Unique environment identifier generated by BCTRL."),
    ]
    """
    Unique environment identifier generated by BCTRL.
    """

    error_code: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="errorCode"), pydantic.Field(alias="errorCode")
    ] = None
    exit_code: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="exitCode"),
        pydantic.Field(
            alias="exitCode",
            description="Process exit code; null until known. A non-zero code is still a completed execution.",
        ),
    ] = None
    """
    Process exit code; null until known. A non-zero code is still a completed execution.
    """

    finished_at: typing_extensions.Annotated[
        typing.Optional[Rfc3339Timestamp], FieldMetadata(alias="finishedAt"), pydantic.Field(alias="finishedAt")
    ] = None
    id: str = pydantic.Field()
    """
    Unique environmentExec identifier generated by BCTRL.
    """

    object: EnvironmentExecObject
    started_at: typing_extensions.Annotated[
        typing.Optional[Rfc3339Timestamp], FieldMetadata(alias="startedAt"), pydantic.Field(alias="startedAt")
    ] = None
    status: EnvironmentExecStatus
    stderr: str
    stderr_truncated: typing_extensions.Annotated[
        bool, FieldMetadata(alias="stderrTruncated"), pydantic.Field(alias="stderrTruncated")
    ]
    stdout: str = pydantic.Field()
    """
    Captured standard output, decoded as UTF-8 with replacement.
    """

    stdout_truncated: typing_extensions.Annotated[
        bool, FieldMetadata(alias="stdoutTruncated"), pydantic.Field(alias="stdoutTruncated")
    ]
    updated_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
