# This file was auto-generated by Fern from our API Definition.

import typing

EnvironmentStatus = typing.Union[
    typing.Literal["provisioning", "ready", "stopping", "stopped", "failed", "deleting"], typing.Any
]
