# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .help_topic_audiences_item import HelpTopicAudiencesItem
from .help_topic_method import HelpTopicMethod


class HelpTopic(UniversalBaseModel):
    aliases: typing.Optional[typing.List[str]] = None
    audiences: typing.List[HelpTopicAudiencesItem]
    method: typing.Optional[HelpTopicMethod] = None
    operation_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="operationId"), pydantic.Field(alias="operationId")
    ] = None
    path: typing.Optional[str] = None
    summary: str
    title: str
    topic: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
