# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .hosted_view_create_response_object import HostedViewCreateResponseObject
from .hosted_view_presentation import HostedViewPresentation
from .resolved_branding import ResolvedBranding
from .rfc3339timestamp import Rfc3339Timestamp
from .view_components import ViewComponents
from .view_scope import ViewScope


class HostedViewCreateResponse(UniversalBaseModel):
    branding: ResolvedBranding
    components: ViewComponents
    control: bool
    conversation_send: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="conversationSend"), pydantic.Field(alias="conversationSend")
    ] = None
    created_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    expires_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="expiresAt"), pydantic.Field(alias="expiresAt")
    ]
    id: str
    object: HostedViewCreateResponseObject
    presentation: HostedViewPresentation
    scope: ViewScope
    token: str = pydantic.Field()
    """
    Short-lived bearer token returned once when a view is created.
    """

    updated_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
