# This file was auto-generated by Fern from our API Definition.

import typing

from .list_browsers_request_status_one_item import ListBrowsersRequestStatusOneItem
from .list_browsers_request_status_zero import ListBrowsersRequestStatusZero

ListBrowsersRequestStatus = typing.Union[ListBrowsersRequestStatusZero, typing.List[ListBrowsersRequestStatusOneItem]]
