# This file was auto-generated by Fern from our API Definition.

import typing

ListTraceRequestKindOneItem = typing.Union[
    typing.Literal["runtime", "agent", "tool", "llm", "browser", "network", "file", "system"], typing.Any
]
