# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .location_home_regions_item import LocationHomeRegionsItem
from .location_id import LocationId
from .location_object import LocationObject
from .location_status import LocationStatus


class Location(UniversalBaseModel):
    home_regions: typing_extensions.Annotated[
        typing.List[LocationHomeRegionsItem], FieldMetadata(alias="homeRegions"), pydantic.Field(alias="homeRegions")
    ]
    id: LocationId
    name: str
    object: LocationObject
    status: LocationStatus

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
