# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .resource_name import ResourceName


class ManagedStaticProxyCreateRequest(UniversalBaseModel):
    auto_renew: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="autoRenew"), pydantic.Field(alias="autoRenew")
    ] = None
    name: typing.Optional[ResourceName] = None
    pool_id: typing_extensions.Annotated[str, FieldMetadata(alias="poolId"), pydantic.Field(alias="poolId")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
