# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .managed_static_proxy_location import ManagedStaticProxyLocation
from .managed_static_proxy_object import ManagedStaticProxyObject
from .managed_static_proxy_pricing import ManagedStaticProxyPricing
from .managed_static_proxy_status import ManagedStaticProxyStatus
from .managed_static_proxy_type import ManagedStaticProxyType
from .resource_name import ResourceName
from .rfc3339timestamp import Rfc3339Timestamp
from .subaccount_id import SubaccountId


class ManagedStaticProxy(UniversalBaseModel):
    assigned_ip: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="assignedIp"), pydantic.Field(alias="assignedIp")
    ] = None
    auto_renew: typing_extensions.Annotated[bool, FieldMetadata(alias="autoRenew"), pydantic.Field(alias="autoRenew")]
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]
    expires_at: typing_extensions.Annotated[
        typing.Optional[Rfc3339Timestamp], FieldMetadata(alias="expiresAt"), pydantic.Field(alias="expiresAt")
    ] = None
    id: str
    location: typing.Optional[ManagedStaticProxyLocation] = None
    name: ResourceName
    object: ManagedStaticProxyObject
    pool_id: typing_extensions.Annotated[str, FieldMetadata(alias="poolId"), pydantic.Field(alias="poolId")]
    pricing: typing.Optional[ManagedStaticProxyPricing] = None
    renews_at: typing_extensions.Annotated[
        typing.Optional[Rfc3339Timestamp], FieldMetadata(alias="renewsAt"), pydantic.Field(alias="renewsAt")
    ] = None
    status: ManagedStaticProxyStatus
    subaccount_id: typing_extensions.Annotated[
        typing.Optional[SubaccountId], FieldMetadata(alias="subaccountId"), pydantic.Field(alias="subaccountId")
    ] = None
    type: ManagedStaticProxyType
    updated_at: typing_extensions.Annotated[str, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
