# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .proxy_pool_category import ProxyPoolCategory
from .proxy_pool_object import ProxyPoolObject


class ProxyPool(UniversalBaseModel):
    available_count: typing_extensions.Annotated[
        int, FieldMetadata(alias="availableCount"), pydantic.Field(alias="availableCount")
    ]
    category: ProxyPoolCategory
    city: typing.Optional[str] = None
    country: str
    id: str
    label: str
    object: ProxyPoolObject
    price_credits: typing_extensions.Annotated[
        int, FieldMetadata(alias="priceCredits"), pydantic.Field(alias="priceCredits")
    ]
    term_days: typing_extensions.Annotated[int, FieldMetadata(alias="termDays"), pydantic.Field(alias="termDays")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
