# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .branding_tokens import BrandingTokens


class ResolvedBranding(UniversalBaseModel):
    logo: typing.Optional[str] = None
    product_name: typing_extensions.Annotated[
        str, FieldMetadata(alias="productName"), pydantic.Field(alias="productName")
    ]
    show_powered_by: typing_extensions.Annotated[
        bool, FieldMetadata(alias="showPoweredBy"), pydantic.Field(alias="showPoweredBy")
    ]
    tokens: BrandingTokens

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
