# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .rfc3339timestamp import Rfc3339Timestamp
from .run_file_binding import RunFileBinding
from .run_file_object import RunFileObject
from .run_file_role import RunFileRole


class RunFile(UniversalBaseModel):
    binding: typing.Optional[RunFileBinding] = None
    created_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    file_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="fileId"),
        pydantic.Field(alias="fileId", description="Unique file identifier generated by BCTRL."),
    ]
    """
    Unique file identifier generated by BCTRL.
    """

    filename: str
    object: RunFileObject
    role: RunFileRole
    runtime_path: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="runtimePath"), pydantic.Field(alias="runtimePath")
    ] = None
    size: int
    source_path: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sourcePath"), pydantic.Field(alias="sourcePath")
    ] = None
    space_path: typing_extensions.Annotated[str, FieldMetadata(alias="spacePath"), pydantic.Field(alias="spacePath")]
    updated_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
