# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .rfc3339timestamp import Rfc3339Timestamp
from .run_usage_billing_status import RunUsageBillingStatus


class RunUsage(UniversalBaseModel):
    ai_tokens_total: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="aiTokensTotal"), pydantic.Field(alias="aiTokensTotal")
    ] = None
    billing_status: typing_extensions.Annotated[
        RunUsageBillingStatus, FieldMetadata(alias="billingStatus"), pydantic.Field(alias="billingStatus")
    ]
    captcha_solves: typing_extensions.Annotated[
        int, FieldMetadata(alias="captchaSolves"), pydantic.Field(alias="captchaSolves")
    ]
    computed_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="computedAt"), pydantic.Field(alias="computedAt")
    ]
    credits_used: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="creditsUsed"), pydantic.Field(alias="creditsUsed")
    ] = None
    files_bytes: typing_extensions.Annotated[int, FieldMetadata(alias="filesBytes"), pydantic.Field(alias="filesBytes")]
    proxy_bytes: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="proxyBytes"), pydantic.Field(alias="proxyBytes")
    ] = None
    runtime_seconds: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="runtimeSeconds"), pydantic.Field(alias="runtimeSeconds")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
