# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .secret_reveal_response_object import SecretRevealResponseObject


class SecretRevealResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Secret path, for example `prod/github/bot`. May contain `/`.
    """

    notes: typing.Optional[str] = None
    object: SecretRevealResponseObject
    password: typing.Optional[str] = None
    totp: typing.Optional[str] = None
    username: typing.Optional[str] = None
    value: typing.Optional[str] = None
    version: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
