# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .json_object import JsonObject
from .resource_name import ResourceName
from .subaccount_id import SubaccountId
from .subaccount_limits import SubaccountLimits
from .subaccount_object import SubaccountObject
from .subaccount_status import SubaccountStatus
from .subaccount_usage import SubaccountUsage


class Subaccount(UniversalBaseModel):
    archived_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="archivedAt"), pydantic.Field(alias="archivedAt")
    ] = None
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]
    default_space_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="defaultSpaceId"), pydantic.Field(alias="defaultSpaceId")
    ]
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    id: SubaccountId
    limits: SubaccountLimits
    metadata: typing.Optional[JsonObject] = None
    name: ResourceName
    object: SubaccountObject
    status: SubaccountStatus
    updated_at: typing_extensions.Annotated[str, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")]
    usage: typing.Optional[SubaccountUsage] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
