# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class TaskArtifact(UniversalBaseModel):
    content_type: typing_extensions.Annotated[
        str, FieldMetadata(alias="contentType"), pydantic.Field(alias="contentType")
    ]
    file_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="fileId"),
        pydantic.Field(alias="fileId", description="Unique file identifier generated by BCTRL."),
    ]
    """
    Unique file identifier generated by BCTRL.
    """

    name: str
    size_bytes: typing_extensions.Annotated[int, FieldMetadata(alias="sizeBytes"), pydantic.Field(alias="sizeBytes")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
