# This file was auto-generated by Fern from our API Definition.

import typing

from .tool_create_request_description_space_id_one import ToolCreateRequestDescriptionSpaceIdOne

ToolCreateRequestDescriptionSpaceId = typing.Union[str, ToolCreateRequestDescriptionSpaceIdOne]
