# This file was auto-generated by Fern from our API Definition.

import typing

from .tool_create_request_description import ToolCreateRequestDescription
from .tool_create_request_one import ToolCreateRequestOne
from .tool_create_request_zero import ToolCreateRequestZero

ToolCreateRequest = typing.Union[ToolCreateRequestZero, ToolCreateRequestOne, ToolCreateRequestDescription]
