# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .tool_create_request_description_implementation_type import ToolCreateRequestDescriptionImplementationType


class ToolCreateRequestDescriptionImplementation(UniversalBaseModel):
    source_turn_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="sourceTurnId"),
        pydantic.Field(alias="sourceTurnId", description="Unique agentTurn identifier generated by BCTRL."),
    ]
    """
    Unique agentTurn identifier generated by BCTRL.
    """

    type: ToolCreateRequestDescriptionImplementationType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
