# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .rfc3339timestamp import Rfc3339Timestamp
from .view_session_status import ViewSessionStatus
from .view_session_surface import ViewSessionSurface
from .view_session_unavailable_reason import ViewSessionUnavailableReason


class ViewSession(UniversalBaseModel):
    duration_seconds: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="durationSeconds"), pydantic.Field(alias="durationSeconds")
    ] = None
    expires_at: typing_extensions.Annotated[
        Rfc3339Timestamp, FieldMetadata(alias="expiresAt"), pydantic.Field(alias="expiresAt")
    ]
    status: typing.Optional[ViewSessionStatus] = None
    surface: ViewSessionSurface
    unavailable_reason: typing_extensions.Annotated[
        typing.Optional[ViewSessionUnavailableReason],
        FieldMetadata(alias="unavailableReason"),
        pydantic.Field(alias="unavailableReason"),
    ] = None
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
