# This file was auto-generated by Fern from our API Definition.

import typing

from .view_scope_conversation_input import ViewScopeConversationInput
from .view_scope_run_input import ViewScopeRunInput
from .view_scope_runtime_input import ViewScopeRuntimeInput
from .view_scope_space_input import ViewScopeSpaceInput

ViewScopeInput = typing.Union[ViewScopeSpaceInput, ViewScopeRuntimeInput, ViewScopeRunInput, ViewScopeConversationInput]
