# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawAiClient, RawAiClient

if typing.TYPE_CHECKING:
    from .credentials.client import AsyncCredentialsClient, CredentialsClient
    from .models.client import AsyncModelsClient, ModelsClient


class AiClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAiClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._credentials: typing.Optional[CredentialsClient] = None
        self._models: typing.Optional[ModelsClient] = None

    @property
    def with_raw_response(self) -> RawAiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAiClient
        """
        return self._raw_client

    @property
    def credentials(self):
        if self._credentials is None:
            from .credentials.client import CredentialsClient  # noqa: E402

            self._credentials = CredentialsClient(client_wrapper=self._client_wrapper)
        return self._credentials

    @property
    def models(self):
        if self._models is None:
            from .models.client import ModelsClient  # noqa: E402

            self._models = ModelsClient(client_wrapper=self._client_wrapper)
        return self._models


class AsyncAiClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAiClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._credentials: typing.Optional[AsyncCredentialsClient] = None
        self._models: typing.Optional[AsyncModelsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawAiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAiClient
        """
        return self._raw_client

    @property
    def credentials(self):
        if self._credentials is None:
            from .credentials.client import AsyncCredentialsClient  # noqa: E402

            self._credentials = AsyncCredentialsClient(client_wrapper=self._client_wrapper)
        return self._credentials

    @property
    def models(self):
        if self._models is None:
            from .models.client import AsyncModelsClient  # noqa: E402

            self._models = AsyncModelsClient(client_wrapper=self._client_wrapper)
        return self._models
