# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.proxy import Proxy
from ..types.proxy_create_request import ProxyCreateRequest
from ..types.proxy_delete_response import ProxyDeleteResponse
from ..types.proxy_list_response import ProxyListResponse
from ..types.proxy_location_pool import ProxyLocationPool
from ..types.proxy_test_response import ProxyTestResponse
from ..types.resource_name import ResourceName
from .raw_client import AsyncRawProxiesClient, RawProxiesClient
from .types.list_proxies_request_order import ListProxiesRequestOrder
from .types.proxy_update_request_device import ProxyUpdateRequestDevice
from .types.proxy_update_request_dns_resolution import ProxyUpdateRequestDnsResolution
from .types.proxy_update_request_ip_family import ProxyUpdateRequestIpFamily
from .types.proxy_update_request_preference import ProxyUpdateRequestPreference
from .types.proxy_update_request_protocol import ProxyUpdateRequestProtocol
from .types.proxy_update_request_rotation import ProxyUpdateRequestRotation
from .types.proxy_update_request_udp_mode import ProxyUpdateRequestUdpMode

if typing.TYPE_CHECKING:
    from .geo.client import AsyncGeoClient, GeoClient
    from .locations.client import AsyncLocationsClient, LocationsClient
    from .pools.client import AsyncPoolsClient, PoolsClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ProxiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProxiesClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._geo: typing.Optional[GeoClient] = None
        self._locations: typing.Optional[LocationsClient] = None
        self._pools: typing.Optional[PoolsClient] = None

    @property
    def with_raw_response(self) -> RawProxiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProxiesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListProxiesRequestOrder] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProxyListResponse:
        """
        List saved proxies using the simplified response envelope.

        Parameters
        ----------
        cursor : typing.Optional[str]

        order : typing.Optional[ListProxiesRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProxyListResponse
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.proxies.list()
        """
        _response = self._raw_client.list(cursor=cursor, order=order, limit=limit, request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        request: ProxyCreateRequest,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Proxy:
        """
        Create a saved proxy configuration for browser runtimes.

        Parameters
        ----------
        request : ProxyCreateRequest

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Proxy
            Created

        Examples
        --------
        from bctrl import Bctrl, ProxyCreateRequest_Custom

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.proxies.create(
            request=ProxyCreateRequest_Custom(),
        )
        """
        _response = self._raw_client.create(
            request=request, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def get(self, proxy_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Proxy:
        """
        Get one saved proxy using the simplified proxy resource shape.

        Parameters
        ----------
        proxy_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Proxy
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.proxies.get(
            proxy_id="proxyId",
        )
        """
        _response = self._raw_client.get(proxy_id, request_options=request_options)
        return _response.data

    def delete(
        self,
        proxy_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProxyDeleteResponse:
        """
        Delete a saved proxy that should no longer be used.

        Parameters
        ----------
        proxy_id : str

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProxyDeleteResponse
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.proxies.delete(
            proxy_id="proxyId",
        )
        """
        _response = self._raw_client.delete(proxy_id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    def update(
        self,
        proxy_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        auto_renew: typing.Optional[bool] = OMIT,
        city: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        device: typing.Optional[ProxyUpdateRequestDevice] = OMIT,
        dns_resolution: typing.Optional[ProxyUpdateRequestDnsResolution] = OMIT,
        geo_id: typing.Optional[str] = OMIT,
        host: typing.Optional[str] = OMIT,
        ip_family: typing.Optional[ProxyUpdateRequestIpFamily] = OMIT,
        isp: typing.Optional[str] = OMIT,
        name: typing.Optional[ResourceName] = OMIT,
        password: typing.Optional[str] = OMIT,
        pool: typing.Optional[ProxyLocationPool] = OMIT,
        port: typing.Optional[int] = OMIT,
        preference: typing.Optional[ProxyUpdateRequestPreference] = OMIT,
        protocol: typing.Optional[ProxyUpdateRequestProtocol] = OMIT,
        region: typing.Optional[str] = OMIT,
        rotation: typing.Optional[ProxyUpdateRequestRotation] = OMIT,
        state: typing.Optional[str] = OMIT,
        sticky_key: typing.Optional[str] = OMIT,
        udp_mode: typing.Optional[ProxyUpdateRequestUdpMode] = OMIT,
        url: typing.Optional[str] = OMIT,
        username: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Proxy:
        """
        Update one saved proxy. Future browser runtimes can use the updated proxy configuration.

        Parameters
        ----------
        proxy_id : str

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        auto_renew : typing.Optional[bool]

        city : typing.Optional[str]

        country : typing.Optional[str]

        device : typing.Optional[ProxyUpdateRequestDevice]

        dns_resolution : typing.Optional[ProxyUpdateRequestDnsResolution]

        geo_id : typing.Optional[str]

        host : typing.Optional[str]

        ip_family : typing.Optional[ProxyUpdateRequestIpFamily]

        isp : typing.Optional[str]

        name : typing.Optional[ResourceName]

        password : typing.Optional[str]
            The proxy password, or a secret reference such as `secret:proxies/office#password`.

        pool : typing.Optional[ProxyLocationPool]

        port : typing.Optional[int]

        preference : typing.Optional[ProxyUpdateRequestPreference]

        protocol : typing.Optional[ProxyUpdateRequestProtocol]

        region : typing.Optional[str]

        rotation : typing.Optional[ProxyUpdateRequestRotation]

        state : typing.Optional[str]

        sticky_key : typing.Optional[str]

        udp_mode : typing.Optional[ProxyUpdateRequestUdpMode]

        url : typing.Optional[str]

        username : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Proxy
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.proxies.update(
            proxy_id="proxyId",
        )
        """
        _response = self._raw_client.update(
            proxy_id,
            idempotency_key=idempotency_key,
            auto_renew=auto_renew,
            city=city,
            country=country,
            device=device,
            dns_resolution=dns_resolution,
            geo_id=geo_id,
            host=host,
            ip_family=ip_family,
            isp=isp,
            name=name,
            password=password,
            pool=pool,
            port=port,
            preference=preference,
            protocol=protocol,
            region=region,
            rotation=rotation,
            state=state,
            sticky_key=sticky_key,
            udp_mode=udp_mode,
            url=url,
            username=username,
            request_options=request_options,
        )
        return _response.data

    def test(
        self,
        proxy_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProxyTestResponse:
        """
        Test a saved proxy configuration before using it with browser runtimes.

        Parameters
        ----------
        proxy_id : str

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProxyTestResponse
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.proxies.test(
            proxy_id="proxyId",
        )
        """
        _response = self._raw_client.test(proxy_id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    @property
    def geo(self):
        if self._geo is None:
            from .geo.client import GeoClient  # noqa: E402

            self._geo = GeoClient(client_wrapper=self._client_wrapper)
        return self._geo

    @property
    def locations(self):
        if self._locations is None:
            from .locations.client import LocationsClient  # noqa: E402

            self._locations = LocationsClient(client_wrapper=self._client_wrapper)
        return self._locations

    @property
    def pools(self):
        if self._pools is None:
            from .pools.client import PoolsClient  # noqa: E402

            self._pools = PoolsClient(client_wrapper=self._client_wrapper)
        return self._pools


class AsyncProxiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProxiesClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._geo: typing.Optional[AsyncGeoClient] = None
        self._locations: typing.Optional[AsyncLocationsClient] = None
        self._pools: typing.Optional[AsyncPoolsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawProxiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProxiesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListProxiesRequestOrder] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProxyListResponse:
        """
        List saved proxies using the simplified response envelope.

        Parameters
        ----------
        cursor : typing.Optional[str]

        order : typing.Optional[ListProxiesRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProxyListResponse
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.proxies.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            cursor=cursor, order=order, limit=limit, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        *,
        request: ProxyCreateRequest,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Proxy:
        """
        Create a saved proxy configuration for browser runtimes.

        Parameters
        ----------
        request : ProxyCreateRequest

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Proxy
            Created

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl, ProxyCreateRequest_Custom

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.proxies.create(
                request=ProxyCreateRequest_Custom(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            request=request, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def get(self, proxy_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Proxy:
        """
        Get one saved proxy using the simplified proxy resource shape.

        Parameters
        ----------
        proxy_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Proxy
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.proxies.get(
                proxy_id="proxyId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(proxy_id, request_options=request_options)
        return _response.data

    async def delete(
        self,
        proxy_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProxyDeleteResponse:
        """
        Delete a saved proxy that should no longer be used.

        Parameters
        ----------
        proxy_id : str

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProxyDeleteResponse
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.proxies.delete(
                proxy_id="proxyId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            proxy_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def update(
        self,
        proxy_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        auto_renew: typing.Optional[bool] = OMIT,
        city: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        device: typing.Optional[ProxyUpdateRequestDevice] = OMIT,
        dns_resolution: typing.Optional[ProxyUpdateRequestDnsResolution] = OMIT,
        geo_id: typing.Optional[str] = OMIT,
        host: typing.Optional[str] = OMIT,
        ip_family: typing.Optional[ProxyUpdateRequestIpFamily] = OMIT,
        isp: typing.Optional[str] = OMIT,
        name: typing.Optional[ResourceName] = OMIT,
        password: typing.Optional[str] = OMIT,
        pool: typing.Optional[ProxyLocationPool] = OMIT,
        port: typing.Optional[int] = OMIT,
        preference: typing.Optional[ProxyUpdateRequestPreference] = OMIT,
        protocol: typing.Optional[ProxyUpdateRequestProtocol] = OMIT,
        region: typing.Optional[str] = OMIT,
        rotation: typing.Optional[ProxyUpdateRequestRotation] = OMIT,
        state: typing.Optional[str] = OMIT,
        sticky_key: typing.Optional[str] = OMIT,
        udp_mode: typing.Optional[ProxyUpdateRequestUdpMode] = OMIT,
        url: typing.Optional[str] = OMIT,
        username: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Proxy:
        """
        Update one saved proxy. Future browser runtimes can use the updated proxy configuration.

        Parameters
        ----------
        proxy_id : str

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        auto_renew : typing.Optional[bool]

        city : typing.Optional[str]

        country : typing.Optional[str]

        device : typing.Optional[ProxyUpdateRequestDevice]

        dns_resolution : typing.Optional[ProxyUpdateRequestDnsResolution]

        geo_id : typing.Optional[str]

        host : typing.Optional[str]

        ip_family : typing.Optional[ProxyUpdateRequestIpFamily]

        isp : typing.Optional[str]

        name : typing.Optional[ResourceName]

        password : typing.Optional[str]
            The proxy password, or a secret reference such as `secret:proxies/office#password`.

        pool : typing.Optional[ProxyLocationPool]

        port : typing.Optional[int]

        preference : typing.Optional[ProxyUpdateRequestPreference]

        protocol : typing.Optional[ProxyUpdateRequestProtocol]

        region : typing.Optional[str]

        rotation : typing.Optional[ProxyUpdateRequestRotation]

        state : typing.Optional[str]

        sticky_key : typing.Optional[str]

        udp_mode : typing.Optional[ProxyUpdateRequestUdpMode]

        url : typing.Optional[str]

        username : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Proxy
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.proxies.update(
                proxy_id="proxyId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            proxy_id,
            idempotency_key=idempotency_key,
            auto_renew=auto_renew,
            city=city,
            country=country,
            device=device,
            dns_resolution=dns_resolution,
            geo_id=geo_id,
            host=host,
            ip_family=ip_family,
            isp=isp,
            name=name,
            password=password,
            pool=pool,
            port=port,
            preference=preference,
            protocol=protocol,
            region=region,
            rotation=rotation,
            state=state,
            sticky_key=sticky_key,
            udp_mode=udp_mode,
            url=url,
            username=username,
            request_options=request_options,
        )
        return _response.data

    async def test(
        self,
        proxy_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProxyTestResponse:
        """
        Test a saved proxy configuration before using it with browser runtimes.

        Parameters
        ----------
        proxy_id : str

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProxyTestResponse
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.proxies.test(
                proxy_id="proxyId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.test(
            proxy_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    @property
    def geo(self):
        if self._geo is None:
            from .geo.client import AsyncGeoClient  # noqa: E402

            self._geo = AsyncGeoClient(client_wrapper=self._client_wrapper)
        return self._geo

    @property
    def locations(self):
        if self._locations is None:
            from .locations.client import AsyncLocationsClient  # noqa: E402

            self._locations = AsyncLocationsClient(client_wrapper=self._client_wrapper)
        return self._locations

    @property
    def pools(self):
        if self._pools is None:
            from .pools.client import AsyncPoolsClient  # noqa: E402

            self._pools = AsyncPoolsClient(client_wrapper=self._client_wrapper)
        return self._pools
