# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.resource_name import ResourceName
from ...types.subaccount_id import SubaccountId

UpdateSubaccountsRequestSubaccountId = typing.Union[SubaccountId, ResourceName]
