# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.batch_computer_request_space_id import BatchComputerRequestSpaceId
from ...types.click_computer_request_space_id import ClickComputerRequestSpaceId
from ...types.computer_action_request import ComputerActionRequest
from ...types.computer_batch_result import ComputerBatchResult
from ...types.computer_result import ComputerResult
from ...types.cursor_computer_request_space_id import CursorComputerRequestSpaceId
from ...types.double_click_computer_request_space_id import DoubleClickComputerRequestSpaceId
from ...types.drag_computer_request_space_id import DragComputerRequestSpaceId
from ...types.key_computer_request_space_id import KeyComputerRequestSpaceId
from ...types.move_computer_request_space_id import MoveComputerRequestSpaceId
from ...types.screenshot_computer_request_space_id import ScreenshotComputerRequestSpaceId
from ...types.scroll_computer_request_space_id import ScrollComputerRequestSpaceId
from ...types.type_computer_request_space_id import TypeComputerRequestSpaceId
from ...types.wait_computer_request_space_id import WaitComputerRequestSpaceId
from .raw_client import AsyncRawComputerClient, RawComputerClient
from .types.browsers_computer_click_request_button import BrowsersComputerClickRequestButton
from .types.browsers_computer_scroll_request_direction import BrowsersComputerScrollRequestDirection

if typing.TYPE_CHECKING:
    from .clipboard.client import AsyncClipboardClient, ClipboardClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ComputerClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawComputerClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._clipboard: typing.Optional[ClipboardClient] = None

    @property
    def with_raw_response(self) -> RawComputerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawComputerClient
        """
        return self._raw_client

    def batch(
        self,
        browser_id: str,
        *,
        actions: typing.Sequence[ComputerActionRequest],
        space_id: typing.Optional[BatchComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerBatchResult:
        """
        Execute up to twenty desktop actions in order on one current Browser Run. Every action is validated before acceptance. Execution stops at the first uncertain result and returns unknown with null data; earlier actions may have taken effect. Reusing the same Idempotency-Key replays the terminal result without repeating the batch.

        Parameters
        ----------
        browser_id : str

        actions : typing.Sequence[ComputerActionRequest]

        space_id : typing.Optional[BatchComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerBatchResult
            OK

        Examples
        --------
        from bctrl import Bctrl, ComputerActionRequest_Screenshot

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.computer.batch(
            browser_id="browserId",
            actions=[ComputerActionRequest_Screenshot()],
        )
        """
        _response = self._raw_client.batch(
            browser_id,
            actions=actions,
            space_id=space_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def click(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[ClickComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        button: typing.Optional[BrowsersComputerClickRequestButton] = OMIT,
        click_count: typing.Optional[int] = OMIT,
        coordinate: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        modifiers: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Click the current Browser Run at screenshot-pixel coordinates, or at the cursor when omitted. Button defaults to left; two or three clicks require the left button. An interrupted action returns unknown and must not be repeated automatically.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[ClickComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        button : typing.Optional[BrowsersComputerClickRequestButton]

        click_count : typing.Optional[int]

        coordinate : typing.Optional[typing.Sequence[typing.Any]]

        modifiers : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.computer.click(
            browser_id="browserId",
        )
        """
        _response = self._raw_client.click(
            browser_id,
            space_id=space_id,
            idempotency_key=idempotency_key,
            button=button,
            click_count=click_count,
            coordinate=coordinate,
            modifiers=modifiers,
            request_options=request_options,
        )
        return _response.data

    def cursor(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[CursorComputerRequestSpaceId] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Read the cursor position and desktop dimensions of the current Browser Run. The result carries its canonical Event ID. Human control blocks automation; interrupted execution returns unknown.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[CursorComputerRequestSpaceId]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.computer.cursor(
            browser_id="browserId",
        )
        """
        _response = self._raw_client.cursor(browser_id, space_id=space_id, request_options=request_options)
        return _response.data

    def double_click(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[DoubleClickComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        coordinate: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        modifiers: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Double-click the left mouse button in the current Browser Run. Coordinates use screenshot pixels; omission uses the current cursor. An interrupted action returns unknown with its accepted Event ID.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[DoubleClickComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        coordinate : typing.Optional[typing.Sequence[typing.Any]]

        modifiers : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.computer.double_click(
            browser_id="browserId",
        )
        """
        _response = self._raw_client.double_click(
            browser_id,
            space_id=space_id,
            idempotency_key=idempotency_key,
            coordinate=coordinate,
            modifiers=modifiers,
            request_options=request_options,
        )
        return _response.data

    def drag(
        self,
        browser_id: str,
        *,
        coordinate: typing.Sequence[typing.Any],
        space_id: typing.Optional[DragComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        modifiers: typing.Optional[str] = OMIT,
        path: typing.Optional[typing.Sequence[typing.Sequence[typing.Any]]] = OMIT,
        start_coordinate: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Drag the left mouse button in the current Browser Run to the requested coordinates, with an optional starting position and bounded path. Human control blocks automation. An interrupted action returns unknown.

        Parameters
        ----------
        browser_id : str

        coordinate : typing.Sequence[typing.Any]

        space_id : typing.Optional[DragComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        modifiers : typing.Optional[str]

        path : typing.Optional[typing.Sequence[typing.Sequence[typing.Any]]]

        start_coordinate : typing.Optional[typing.Sequence[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.computer.drag(
            browser_id="browserId",
            coordinate=[],
        )
        """
        _response = self._raw_client.drag(
            browser_id,
            coordinate=coordinate,
            space_id=space_id,
            idempotency_key=idempotency_key,
            modifiers=modifiers,
            path=path,
            start_coordinate=start_coordinate,
            request_options=request_options,
        )
        return _response.data

    def key(
        self,
        browser_id: str,
        *,
        keys: str,
        space_id: typing.Optional[KeyComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        repeat: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Send one bounded key chord to the current Browser Run, with an optional repeat count. Human control blocks automation. An interrupted action returns unknown with its accepted Event ID.

        Parameters
        ----------
        browser_id : str

        keys : str

        space_id : typing.Optional[KeyComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        repeat : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.computer.key(
            browser_id="browserId",
            keys="keys",
        )
        """
        _response = self._raw_client.key(
            browser_id,
            keys=keys,
            space_id=space_id,
            idempotency_key=idempotency_key,
            repeat=repeat,
            request_options=request_options,
        )
        return _response.data

    def move(
        self,
        browser_id: str,
        *,
        coordinate: typing.Sequence[typing.Any],
        space_id: typing.Optional[MoveComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Move the cursor in the current Browser Run to screenshot-pixel coordinates. Human control blocks automation. An interrupted action returns unknown with its accepted Event ID.

        Parameters
        ----------
        browser_id : str

        coordinate : typing.Sequence[typing.Any]

        space_id : typing.Optional[MoveComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.computer.move(
            browser_id="browserId",
            coordinate=[],
        )
        """
        _response = self._raw_client.move(
            browser_id,
            coordinate=coordinate,
            space_id=space_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def screenshot(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[ScreenshotComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Capture the headed desktop of the current Browser Run as a JPEG. The result carries its canonical Event ID. An interrupted capture returns unknown with null data.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[ScreenshotComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.computer.screenshot(
            browser_id="browserId",
        )
        """
        _response = self._raw_client.screenshot(
            browser_id, space_id=space_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def scroll(
        self,
        browser_id: str,
        *,
        amount: int,
        direction: BrowsersComputerScrollRequestDirection,
        space_id: typing.Optional[ScrollComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        coordinate: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        modifiers: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Scroll the current Browser Run in the requested direction by a bounded amount, optionally at screenshot-pixel coordinates. Human control blocks automation. An interrupted action returns unknown.

        Parameters
        ----------
        browser_id : str

        amount : int

        direction : BrowsersComputerScrollRequestDirection

        space_id : typing.Optional[ScrollComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        coordinate : typing.Optional[typing.Sequence[typing.Any]]

        modifiers : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.computer.scroll(
            browser_id="browserId",
            amount=1,
            direction="up",
        )
        """
        _response = self._raw_client.scroll(
            browser_id,
            amount=amount,
            direction=direction,
            space_id=space_id,
            idempotency_key=idempotency_key,
            coordinate=coordinate,
            modifiers=modifiers,
            request_options=request_options,
        )
        return _response.data

    def type(
        self,
        browser_id: str,
        *,
        text: str,
        space_id: typing.Optional[TypeComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Type text into the focused control in the current Browser Run. Text is excluded from canonical capability Events and replay results are encrypted. Human control blocks automation; an interrupted action returns unknown.

        Parameters
        ----------
        browser_id : str

        text : str

        space_id : typing.Optional[TypeComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.computer.type(
            browser_id="browserId",
            text="text",
        )
        """
        _response = self._raw_client.type(
            browser_id, text=text, space_id=space_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def wait(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[WaitComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        duration: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Wait up to ten seconds in the current Browser Run. Human control blocks automation. The result carries its canonical Event ID; interrupted execution returns unknown.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[WaitComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        duration : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.computer.wait(
            browser_id="browserId",
        )
        """
        _response = self._raw_client.wait(
            browser_id,
            space_id=space_id,
            idempotency_key=idempotency_key,
            duration=duration,
            request_options=request_options,
        )
        return _response.data

    @property
    def clipboard(self):
        if self._clipboard is None:
            from .clipboard.client import ClipboardClient  # noqa: E402

            self._clipboard = ClipboardClient(client_wrapper=self._client_wrapper)
        return self._clipboard


class AsyncComputerClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawComputerClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._clipboard: typing.Optional[AsyncClipboardClient] = None

    @property
    def with_raw_response(self) -> AsyncRawComputerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawComputerClient
        """
        return self._raw_client

    async def batch(
        self,
        browser_id: str,
        *,
        actions: typing.Sequence[ComputerActionRequest],
        space_id: typing.Optional[BatchComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerBatchResult:
        """
        Execute up to twenty desktop actions in order on one current Browser Run. Every action is validated before acceptance. Execution stops at the first uncertain result and returns unknown with null data; earlier actions may have taken effect. Reusing the same Idempotency-Key replays the terminal result without repeating the batch.

        Parameters
        ----------
        browser_id : str

        actions : typing.Sequence[ComputerActionRequest]

        space_id : typing.Optional[BatchComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerBatchResult
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl, ComputerActionRequest_Screenshot

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.computer.batch(
                browser_id="browserId",
                actions=[ComputerActionRequest_Screenshot()],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.batch(
            browser_id,
            actions=actions,
            space_id=space_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def click(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[ClickComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        button: typing.Optional[BrowsersComputerClickRequestButton] = OMIT,
        click_count: typing.Optional[int] = OMIT,
        coordinate: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        modifiers: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Click the current Browser Run at screenshot-pixel coordinates, or at the cursor when omitted. Button defaults to left; two or three clicks require the left button. An interrupted action returns unknown and must not be repeated automatically.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[ClickComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        button : typing.Optional[BrowsersComputerClickRequestButton]

        click_count : typing.Optional[int]

        coordinate : typing.Optional[typing.Sequence[typing.Any]]

        modifiers : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.computer.click(
                browser_id="browserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.click(
            browser_id,
            space_id=space_id,
            idempotency_key=idempotency_key,
            button=button,
            click_count=click_count,
            coordinate=coordinate,
            modifiers=modifiers,
            request_options=request_options,
        )
        return _response.data

    async def cursor(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[CursorComputerRequestSpaceId] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Read the cursor position and desktop dimensions of the current Browser Run. The result carries its canonical Event ID. Human control blocks automation; interrupted execution returns unknown.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[CursorComputerRequestSpaceId]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.computer.cursor(
                browser_id="browserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cursor(browser_id, space_id=space_id, request_options=request_options)
        return _response.data

    async def double_click(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[DoubleClickComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        coordinate: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        modifiers: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Double-click the left mouse button in the current Browser Run. Coordinates use screenshot pixels; omission uses the current cursor. An interrupted action returns unknown with its accepted Event ID.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[DoubleClickComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        coordinate : typing.Optional[typing.Sequence[typing.Any]]

        modifiers : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.computer.double_click(
                browser_id="browserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.double_click(
            browser_id,
            space_id=space_id,
            idempotency_key=idempotency_key,
            coordinate=coordinate,
            modifiers=modifiers,
            request_options=request_options,
        )
        return _response.data

    async def drag(
        self,
        browser_id: str,
        *,
        coordinate: typing.Sequence[typing.Any],
        space_id: typing.Optional[DragComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        modifiers: typing.Optional[str] = OMIT,
        path: typing.Optional[typing.Sequence[typing.Sequence[typing.Any]]] = OMIT,
        start_coordinate: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Drag the left mouse button in the current Browser Run to the requested coordinates, with an optional starting position and bounded path. Human control blocks automation. An interrupted action returns unknown.

        Parameters
        ----------
        browser_id : str

        coordinate : typing.Sequence[typing.Any]

        space_id : typing.Optional[DragComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        modifiers : typing.Optional[str]

        path : typing.Optional[typing.Sequence[typing.Sequence[typing.Any]]]

        start_coordinate : typing.Optional[typing.Sequence[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.computer.drag(
                browser_id="browserId",
                coordinate=[],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.drag(
            browser_id,
            coordinate=coordinate,
            space_id=space_id,
            idempotency_key=idempotency_key,
            modifiers=modifiers,
            path=path,
            start_coordinate=start_coordinate,
            request_options=request_options,
        )
        return _response.data

    async def key(
        self,
        browser_id: str,
        *,
        keys: str,
        space_id: typing.Optional[KeyComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        repeat: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Send one bounded key chord to the current Browser Run, with an optional repeat count. Human control blocks automation. An interrupted action returns unknown with its accepted Event ID.

        Parameters
        ----------
        browser_id : str

        keys : str

        space_id : typing.Optional[KeyComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        repeat : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.computer.key(
                browser_id="browserId",
                keys="keys",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.key(
            browser_id,
            keys=keys,
            space_id=space_id,
            idempotency_key=idempotency_key,
            repeat=repeat,
            request_options=request_options,
        )
        return _response.data

    async def move(
        self,
        browser_id: str,
        *,
        coordinate: typing.Sequence[typing.Any],
        space_id: typing.Optional[MoveComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Move the cursor in the current Browser Run to screenshot-pixel coordinates. Human control blocks automation. An interrupted action returns unknown with its accepted Event ID.

        Parameters
        ----------
        browser_id : str

        coordinate : typing.Sequence[typing.Any]

        space_id : typing.Optional[MoveComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.computer.move(
                browser_id="browserId",
                coordinate=[],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.move(
            browser_id,
            coordinate=coordinate,
            space_id=space_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def screenshot(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[ScreenshotComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Capture the headed desktop of the current Browser Run as a JPEG. The result carries its canonical Event ID. An interrupted capture returns unknown with null data.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[ScreenshotComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.computer.screenshot(
                browser_id="browserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.screenshot(
            browser_id, space_id=space_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def scroll(
        self,
        browser_id: str,
        *,
        amount: int,
        direction: BrowsersComputerScrollRequestDirection,
        space_id: typing.Optional[ScrollComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        coordinate: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        modifiers: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Scroll the current Browser Run in the requested direction by a bounded amount, optionally at screenshot-pixel coordinates. Human control blocks automation. An interrupted action returns unknown.

        Parameters
        ----------
        browser_id : str

        amount : int

        direction : BrowsersComputerScrollRequestDirection

        space_id : typing.Optional[ScrollComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        coordinate : typing.Optional[typing.Sequence[typing.Any]]

        modifiers : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.computer.scroll(
                browser_id="browserId",
                amount=1,
                direction="up",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.scroll(
            browser_id,
            amount=amount,
            direction=direction,
            space_id=space_id,
            idempotency_key=idempotency_key,
            coordinate=coordinate,
            modifiers=modifiers,
            request_options=request_options,
        )
        return _response.data

    async def type(
        self,
        browser_id: str,
        *,
        text: str,
        space_id: typing.Optional[TypeComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Type text into the focused control in the current Browser Run. Text is excluded from canonical capability Events and replay results are encrypted. Human control blocks automation; an interrupted action returns unknown.

        Parameters
        ----------
        browser_id : str

        text : str

        space_id : typing.Optional[TypeComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.computer.type(
                browser_id="browserId",
                text="text",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.type(
            browser_id, text=text, space_id=space_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def wait(
        self,
        browser_id: str,
        *,
        space_id: typing.Optional[WaitComputerRequestSpaceId] = None,
        idempotency_key: typing.Optional[str] = None,
        duration: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ComputerResult:
        """
        Wait up to ten seconds in the current Browser Run. Human control blocks automation. The result carries its canonical Event ID; interrupted execution returns unknown.

        Parameters
        ----------
        browser_id : str

        space_id : typing.Optional[WaitComputerRequestSpaceId]

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        duration : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ComputerResult
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.computer.wait(
                browser_id="browserId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.wait(
            browser_id,
            space_id=space_id,
            idempotency_key=idempotency_key,
            duration=duration,
            request_options=request_options,
        )
        return _response.data

    @property
    def clipboard(self):
        if self._clipboard is None:
            from .clipboard.client import AsyncClipboardClient  # noqa: E402

            self._clipboard = AsyncClipboardClient(client_wrapper=self._client_wrapper)
        return self._clipboard
