# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.trace_span_list_response import TraceSpanListResponse
from .raw_client import AsyncRawTraceClient, RawTraceClient
from .types.list_trace_request_kind_item import ListTraceRequestKindItem
from .types.list_trace_request_order import ListTraceRequestOrder
from .types.list_trace_request_resource_type import ListTraceRequestResourceType
from .types.list_trace_request_status_item import ListTraceRequestStatusItem


class TraceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTraceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTraceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTraceClient
        """
        return self._raw_client

    def list(
        self,
        run_id: str,
        *,
        parent_id: typing.Optional[str] = None,
        kind: typing.Optional[typing.Union[ListTraceRequestKindItem, typing.Sequence[ListTraceRequestKindItem]]] = None,
        status: typing.Optional[
            typing.Union[ListTraceRequestStatusItem, typing.Sequence[ListTraceRequestStatusItem]]
        ] = None,
        resource_type: typing.Optional[ListTraceRequestResourceType] = None,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListTraceRequestOrder] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TraceSpanListResponse:
        """
        List structured trace spans for a run.

        Parameters
        ----------
        run_id : str
            Unique run identifier generated by BCTRL.

        parent_id : typing.Optional[str]

        kind : typing.Optional[typing.Union[ListTraceRequestKindItem, typing.Sequence[ListTraceRequestKindItem]]]
            Filter by one or more trace span kinds. Repeat the query parameter for multiple values.

        status : typing.Optional[typing.Union[ListTraceRequestStatusItem, typing.Sequence[ListTraceRequestStatusItem]]]
            Filter by one or more trace span statuses. Repeat the query parameter for multiple values.

        resource_type : typing.Optional[ListTraceRequestResourceType]

        cursor : typing.Optional[str]

        order : typing.Optional[ListTraceRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TraceSpanListResponse
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.runs.trace.list(
            run_id="runId",
        )
        """
        _response = self._raw_client.list(
            run_id,
            parent_id=parent_id,
            kind=kind,
            status=status,
            resource_type=resource_type,
            cursor=cursor,
            order=order,
            limit=limit,
            request_options=request_options,
        )
        return _response.data


class AsyncTraceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTraceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTraceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTraceClient
        """
        return self._raw_client

    async def list(
        self,
        run_id: str,
        *,
        parent_id: typing.Optional[str] = None,
        kind: typing.Optional[typing.Union[ListTraceRequestKindItem, typing.Sequence[ListTraceRequestKindItem]]] = None,
        status: typing.Optional[
            typing.Union[ListTraceRequestStatusItem, typing.Sequence[ListTraceRequestStatusItem]]
        ] = None,
        resource_type: typing.Optional[ListTraceRequestResourceType] = None,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListTraceRequestOrder] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TraceSpanListResponse:
        """
        List structured trace spans for a run.

        Parameters
        ----------
        run_id : str
            Unique run identifier generated by BCTRL.

        parent_id : typing.Optional[str]

        kind : typing.Optional[typing.Union[ListTraceRequestKindItem, typing.Sequence[ListTraceRequestKindItem]]]
            Filter by one or more trace span kinds. Repeat the query parameter for multiple values.

        status : typing.Optional[typing.Union[ListTraceRequestStatusItem, typing.Sequence[ListTraceRequestStatusItem]]]
            Filter by one or more trace span statuses. Repeat the query parameter for multiple values.

        resource_type : typing.Optional[ListTraceRequestResourceType]

        cursor : typing.Optional[str]

        order : typing.Optional[ListTraceRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TraceSpanListResponse
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.runs.trace.list(
                run_id="runId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            run_id,
            parent_id=parent_id,
            kind=kind,
            status=status,
            resource_type=resource_type,
            cursor=cursor,
            order=order,
            limit=limit,
            request_options=request_options,
        )
        return _response.data
