# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.locations_list_response import LocationsListResponse
from .raw_client import AsyncRawLocationsClient, RawLocationsClient
from .types.list_locations_request_order import ListLocationsRequestOrder


class LocationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLocationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLocationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLocationsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListLocationsRequestOrder] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LocationsListResponse:
        """
        List deployed compute locations and current admission availability. Runtime location auto resolves to an allowed live location; homeRegions identifies compatible data homes. Catalog entries are ordered by their immutable ID.

        Parameters
        ----------
        cursor : typing.Optional[str]

        order : typing.Optional[ListLocationsRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LocationsListResponse
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.locations.list()
        """
        _response = self._raw_client.list(cursor=cursor, order=order, limit=limit, request_options=request_options)
        return _response.data


class AsyncLocationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLocationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLocationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLocationsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListLocationsRequestOrder] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LocationsListResponse:
        """
        List deployed compute locations and current admission availability. Runtime location auto resolves to an allowed live location; homeRegions identifies compatible data homes. Catalog entries are ordered by their immutable ID.

        Parameters
        ----------
        cursor : typing.Optional[str]

        order : typing.Optional[ListLocationsRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LocationsListResponse
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.locations.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            cursor=cursor, order=order, limit=limit, request_options=request_options
        )
        return _response.data
