# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.browsers_runs_list_response import BrowsersRunsListResponse
from ...types.list_runs_request_space_id import ListRunsRequestSpaceId
from ...types.list_runs_request_status import ListRunsRequestStatus
from ...types.rfc3339timestamp import Rfc3339Timestamp
from .raw_client import AsyncRawRunsClient, RawRunsClient
from .types.list_runs_request_include import ListRunsRequestInclude
from .types.list_runs_request_order import ListRunsRequestOrder


class RunsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRunsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRunsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRunsClient
        """
        return self._raw_client

    def list(
        self,
        browser_id: str,
        *,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListRunsRequestOrder] = None,
        limit: typing.Optional[int] = None,
        space_id: typing.Optional[ListRunsRequestSpaceId] = None,
        status: typing.Optional[ListRunsRequestStatus] = None,
        from_: typing.Optional[Rfc3339Timestamp] = None,
        to: typing.Optional[Rfc3339Timestamp] = None,
        include: typing.Optional[ListRunsRequestInclude] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BrowsersRunsListResponse:
        """
        List the retained Runs belonging to this browser, including ended and failed Runs, using cursor pagination.

        Parameters
        ----------
        browser_id : str

        cursor : typing.Optional[str]

        order : typing.Optional[ListRunsRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        space_id : typing.Optional[ListRunsRequestSpaceId]

        status : typing.Optional[ListRunsRequestStatus]

        from_ : typing.Optional[Rfc3339Timestamp]

        to : typing.Optional[Rfc3339Timestamp]

        include : typing.Optional[ListRunsRequestInclude]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BrowsersRunsListResponse
            OK

        Examples
        --------
        import datetime

        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.browsers.runs.list(
            browser_id="browserId",
            from_=datetime.datetime.fromisoformat(
                "2026-07-26 12:00:00+00:00",
            ),
            to=datetime.datetime.fromisoformat(
                "2026-07-26 12:00:00+00:00",
            ),
        )
        """
        _response = self._raw_client.list(
            browser_id,
            cursor=cursor,
            order=order,
            limit=limit,
            space_id=space_id,
            status=status,
            from_=from_,
            to=to,
            include=include,
            request_options=request_options,
        )
        return _response.data


class AsyncRunsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRunsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRunsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRunsClient
        """
        return self._raw_client

    async def list(
        self,
        browser_id: str,
        *,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListRunsRequestOrder] = None,
        limit: typing.Optional[int] = None,
        space_id: typing.Optional[ListRunsRequestSpaceId] = None,
        status: typing.Optional[ListRunsRequestStatus] = None,
        from_: typing.Optional[Rfc3339Timestamp] = None,
        to: typing.Optional[Rfc3339Timestamp] = None,
        include: typing.Optional[ListRunsRequestInclude] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BrowsersRunsListResponse:
        """
        List the retained Runs belonging to this browser, including ended and failed Runs, using cursor pagination.

        Parameters
        ----------
        browser_id : str

        cursor : typing.Optional[str]

        order : typing.Optional[ListRunsRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        space_id : typing.Optional[ListRunsRequestSpaceId]

        status : typing.Optional[ListRunsRequestStatus]

        from_ : typing.Optional[Rfc3339Timestamp]

        to : typing.Optional[Rfc3339Timestamp]

        include : typing.Optional[ListRunsRequestInclude]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BrowsersRunsListResponse
            OK

        Examples
        --------
        import asyncio
        import datetime

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.browsers.runs.list(
                browser_id="browserId",
                from_=datetime.datetime.fromisoformat(
                    "2026-07-26 12:00:00+00:00",
                ),
                to=datetime.datetime.fromisoformat(
                    "2026-07-26 12:00:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            browser_id,
            cursor=cursor,
            order=order,
            limit=limit,
            space_id=space_id,
            status=status,
            from_=from_,
            to=to,
            include=include,
            request_options=request_options,
        )
        return _response.data
