# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.datetime_utils import serialize_datetime
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.jsonable_encoder import encode_path_param
from ...core.parse_error import ParsingError
from ...core.pydantic_utilities import parse_obj_as
from ...core.request_options import RequestOptions
from ...core.serialization import convert_and_respect_annotation_metadata
from ...errors.forbidden_error import ForbiddenError
from ...errors.not_found_error import NotFoundError
from ...errors.unauthorized_error import UnauthorizedError
from ...types.browsers_runs_list_response import BrowsersRunsListResponse
from ...types.list_runs_request_space_id import ListRunsRequestSpaceId
from ...types.list_runs_request_status import ListRunsRequestStatus
from ...types.rfc3339timestamp import Rfc3339Timestamp
from .types.list_runs_request_include import ListRunsRequestInclude
from .types.list_runs_request_order import ListRunsRequestOrder
from pydantic import ValidationError


class RawRunsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        browser_id: str,
        *,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListRunsRequestOrder] = None,
        limit: typing.Optional[int] = None,
        space_id: typing.Optional[ListRunsRequestSpaceId] = None,
        status: typing.Optional[ListRunsRequestStatus] = None,
        from_: typing.Optional[Rfc3339Timestamp] = None,
        to: typing.Optional[Rfc3339Timestamp] = None,
        include: typing.Optional[ListRunsRequestInclude] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BrowsersRunsListResponse]:
        """
        List the retained Runs belonging to this browser, including ended and failed Runs, using cursor pagination.

        Parameters
        ----------
        browser_id : str

        cursor : typing.Optional[str]

        order : typing.Optional[ListRunsRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        space_id : typing.Optional[ListRunsRequestSpaceId]

        status : typing.Optional[ListRunsRequestStatus]

        from_ : typing.Optional[Rfc3339Timestamp]

        to : typing.Optional[Rfc3339Timestamp]

        include : typing.Optional[ListRunsRequestInclude]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BrowsersRunsListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/browsers/{encode_path_param(browser_id)}/runs",
            method="GET",
            params={
                "cursor": cursor,
                "order": order,
                "limit": limit,
                "spaceId": space_id,
                "status": convert_and_respect_annotation_metadata(
                    object_=status, annotation=ListRunsRequestStatus, direction="write"
                ),
                "from": serialize_datetime(from_) if from_ is not None else None,
                "to": serialize_datetime(to) if to is not None else None,
                "include": include,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BrowsersRunsListResponse,
                    parse_obj_as(
                        type_=BrowsersRunsListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawRunsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        browser_id: str,
        *,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListRunsRequestOrder] = None,
        limit: typing.Optional[int] = None,
        space_id: typing.Optional[ListRunsRequestSpaceId] = None,
        status: typing.Optional[ListRunsRequestStatus] = None,
        from_: typing.Optional[Rfc3339Timestamp] = None,
        to: typing.Optional[Rfc3339Timestamp] = None,
        include: typing.Optional[ListRunsRequestInclude] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BrowsersRunsListResponse]:
        """
        List the retained Runs belonging to this browser, including ended and failed Runs, using cursor pagination.

        Parameters
        ----------
        browser_id : str

        cursor : typing.Optional[str]

        order : typing.Optional[ListRunsRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        space_id : typing.Optional[ListRunsRequestSpaceId]

        status : typing.Optional[ListRunsRequestStatus]

        from_ : typing.Optional[Rfc3339Timestamp]

        to : typing.Optional[Rfc3339Timestamp]

        include : typing.Optional[ListRunsRequestInclude]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BrowsersRunsListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/browsers/{encode_path_param(browser_id)}/runs",
            method="GET",
            params={
                "cursor": cursor,
                "order": order,
                "limit": limit,
                "spaceId": space_id,
                "status": convert_and_respect_annotation_metadata(
                    object_=status, annotation=ListRunsRequestStatus, direction="write"
                ),
                "from": serialize_datetime(from_) if from_ is not None else None,
                "to": serialize_datetime(to) if to is not None else None,
                "include": include,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BrowsersRunsListResponse,
                    parse_obj_as(
                        type_=BrowsersRunsListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
