# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.file import File
from ..types.file_delete_response import FileDeleteResponse
from ..types.file_list_response import FileListResponse
from ..types.json_object import JsonObject
from ..types.rfc3339timestamp import Rfc3339Timestamp
from .raw_client import AsyncRawFilesClient, RawFilesClient
from .types.list_files_request_include import ListFilesRequestInclude
from .types.list_files_request_order import ListFilesRequestOrder
from .types.list_files_request_source import ListFilesRequestSource

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFilesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        space_id: typing.Optional[str] = None,
        source: typing.Optional[ListFilesRequestSource] = None,
        path: typing.Optional[str] = None,
        prefix: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        run_id: typing.Optional[str] = None,
        runtime_id: typing.Optional[str] = None,
        type: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        created_after: typing.Optional[Rfc3339Timestamp] = None,
        include: typing.Optional[ListFilesRequestInclude] = None,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListFilesRequestOrder] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileListResponse:
        """
        List the canonical durable File resource. Runtime file endpoints operate on a live machine disk: collect turns a machine file into a durable File, while stage performs the reverse. Use source, type, runId, runtimeId, path, prefix, and createdAfter filters here.

        Parameters
        ----------
        space_id : typing.Optional[str]
            Filter by a prefixed space ID, or pass `default` to use the caller default space.

        source : typing.Optional[ListFilesRequestSource]

        path : typing.Optional[str]

        prefix : typing.Optional[str]

        q : typing.Optional[str]

        run_id : typing.Optional[str]

        runtime_id : typing.Optional[str]

        type : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Filter by one or more file artifact types. Repeat the query parameter for multiple values.

        created_after : typing.Optional[Rfc3339Timestamp]

        include : typing.Optional[ListFilesRequestInclude]

        cursor : typing.Optional[str]

        order : typing.Optional[ListFilesRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileListResponse
            OK

        Examples
        --------
        import datetime

        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.files.list(
            created_after=datetime.datetime.fromisoformat(
                "2026-07-26 12:00:00+00:00",
            ),
        )
        """
        _response = self._raw_client.list(
            space_id=space_id,
            source=source,
            path=path,
            prefix=prefix,
            q=q,
            run_id=run_id,
            runtime_id=runtime_id,
            type=type,
            created_after=created_after,
            include=include,
            cursor=cursor,
            order=order,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    def upload(
        self,
        *,
        file: core.File,
        space_id: typing.Optional[str] = None,
        idempotency_key: typing.Optional[str] = None,
        filename: typing.Optional[str] = OMIT,
        metadata: typing.Optional[str] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> File:
        """
        Upload a file into a space and return the canonical file resource.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        space_id : typing.Optional[str]
            Filter by a prefixed space ID, or pass `default` to use the caller default space.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        filename : typing.Optional[str]
            Optional display filename.

        metadata : typing.Optional[str]
            Optional JSON object string with caller-owned file metadata.

        path : typing.Optional[str]
            Optional relative destination path. Must not be absolute or contain . or .. path segments.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        File
            Created

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.files.upload()
        """
        _response = self._raw_client.upload(
            file=file,
            space_id=space_id,
            idempotency_key=idempotency_key,
            filename=filename,
            metadata=metadata,
            path=path,
            request_options=request_options,
        )
        return _response.data

    def get(
        self,
        file_id: str,
        *,
        run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> File:
        """
        Get one file metadata record using the canonical file resource.

        Parameters
        ----------
        file_id : str
            Unique file identifier generated by BCTRL.

        run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        File
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.files.get(
            file_id="fileId",
        )
        """
        _response = self._raw_client.get(file_id, run_id=run_id, request_options=request_options)
        return _response.data

    def delete(
        self,
        file_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileDeleteResponse:
        """
        Delete one uploaded or collected file.

        Parameters
        ----------
        file_id : str
            Unique file identifier generated by BCTRL.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileDeleteResponse
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.files.delete(
            file_id="fileId",
        )
        """
        _response = self._raw_client.delete(file_id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    def update(
        self,
        file_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        filename: typing.Optional[str] = OMIT,
        metadata: typing.Optional[JsonObject] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> File:
        """
        Update one file display name or caller-owned metadata.

        Parameters
        ----------
        file_id : str
            Unique file identifier generated by BCTRL.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        filename : typing.Optional[str]

        metadata : typing.Optional[JsonObject]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        File
            OK

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.files.update(
            file_id="fileId",
        )
        """
        _response = self._raw_client.update(
            file_id,
            idempotency_key=idempotency_key,
            filename=filename,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def content(
        self,
        file_id: str,
        *,
        run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[bytes]:
        """
        Download the bytes for one file.

        Parameters
        ----------
        file_id : str
            Unique file identifier generated by BCTRL.

        run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            File content stream

        Examples
        --------
        from bctrl import Bctrl

        client = Bctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )
        client.files.content(
            file_id="fileId",
        )
        """
        with self._raw_client.content(file_id, run_id=run_id, request_options=request_options) as r:
            yield from r.data


class AsyncFilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFilesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        space_id: typing.Optional[str] = None,
        source: typing.Optional[ListFilesRequestSource] = None,
        path: typing.Optional[str] = None,
        prefix: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        run_id: typing.Optional[str] = None,
        runtime_id: typing.Optional[str] = None,
        type: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        created_after: typing.Optional[Rfc3339Timestamp] = None,
        include: typing.Optional[ListFilesRequestInclude] = None,
        cursor: typing.Optional[str] = None,
        order: typing.Optional[ListFilesRequestOrder] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileListResponse:
        """
        List the canonical durable File resource. Runtime file endpoints operate on a live machine disk: collect turns a machine file into a durable File, while stage performs the reverse. Use source, type, runId, runtimeId, path, prefix, and createdAfter filters here.

        Parameters
        ----------
        space_id : typing.Optional[str]
            Filter by a prefixed space ID, or pass `default` to use the caller default space.

        source : typing.Optional[ListFilesRequestSource]

        path : typing.Optional[str]

        prefix : typing.Optional[str]

        q : typing.Optional[str]

        run_id : typing.Optional[str]

        runtime_id : typing.Optional[str]

        type : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Filter by one or more file artifact types. Repeat the query parameter for multiple values.

        created_after : typing.Optional[Rfc3339Timestamp]

        include : typing.Optional[ListFilesRequestInclude]

        cursor : typing.Optional[str]

        order : typing.Optional[ListFilesRequestOrder]
            Order by createdAt and ID. Defaults to desc.

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileListResponse
            OK

        Examples
        --------
        import asyncio
        import datetime

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.files.list(
                created_after=datetime.datetime.fromisoformat(
                    "2026-07-26 12:00:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            space_id=space_id,
            source=source,
            path=path,
            prefix=prefix,
            q=q,
            run_id=run_id,
            runtime_id=runtime_id,
            type=type,
            created_after=created_after,
            include=include,
            cursor=cursor,
            order=order,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    async def upload(
        self,
        *,
        file: core.File,
        space_id: typing.Optional[str] = None,
        idempotency_key: typing.Optional[str] = None,
        filename: typing.Optional[str] = OMIT,
        metadata: typing.Optional[str] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> File:
        """
        Upload a file into a space and return the canonical file resource.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        space_id : typing.Optional[str]
            Filter by a prefixed space ID, or pass `default` to use the caller default space.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        filename : typing.Optional[str]
            Optional display filename.

        metadata : typing.Optional[str]
            Optional JSON object string with caller-owned file metadata.

        path : typing.Optional[str]
            Optional relative destination path. Must not be absolute or contain . or .. path segments.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        File
            Created

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.files.upload()


        asyncio.run(main())
        """
        _response = await self._raw_client.upload(
            file=file,
            space_id=space_id,
            idempotency_key=idempotency_key,
            filename=filename,
            metadata=metadata,
            path=path,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self,
        file_id: str,
        *,
        run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> File:
        """
        Get one file metadata record using the canonical file resource.

        Parameters
        ----------
        file_id : str
            Unique file identifier generated by BCTRL.

        run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        File
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.files.get(
                file_id="fileId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(file_id, run_id=run_id, request_options=request_options)
        return _response.data

    async def delete(
        self,
        file_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileDeleteResponse:
        """
        Delete one uploaded or collected file.

        Parameters
        ----------
        file_id : str
            Unique file identifier generated by BCTRL.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileDeleteResponse
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.files.delete(
                file_id="fileId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            file_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def update(
        self,
        file_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        filename: typing.Optional[str] = OMIT,
        metadata: typing.Optional[JsonObject] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> File:
        """
        Update one file display name or caller-owned metadata.

        Parameters
        ----------
        file_id : str
            Unique file identifier generated by BCTRL.

        idempotency_key : typing.Optional[str]
            Optional retry key for this billable operation. Reusing the same key with the same request replays its stable outcome; credential-bearing results may be freshly issued for the same principal. Reusing it with a different request returns 409.

        filename : typing.Optional[str]

        metadata : typing.Optional[JsonObject]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        File
            OK

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.files.update(
                file_id="fileId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            file_id,
            idempotency_key=idempotency_key,
            filename=filename,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def content(
        self,
        file_id: str,
        *,
        run_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[bytes]:
        """
        Download the bytes for one file.

        Parameters
        ----------
        file_id : str
            Unique file identifier generated by BCTRL.

        run_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            File content stream

        Examples
        --------
        import asyncio

        from bctrl import AsyncBctrl

        client = AsyncBctrl(
            bctrl_space="YOUR_BCTRL_SPACE",
            bctrl_subaccount_id="YOUR_BCTRL_SUBACCOUNT_ID",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.files.content(
                file_id="fileId",
            )


        asyncio.run(main())
        """
        async with self._raw_client.content(file_id, run_id=run_id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk
